/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto3";

package goonami.proto;

option go_package = "github.com/google/goonami-scanner/core/config/config_go_proto";

option java_multiple_files = true;
option java_outer_classname = "ConfigOuterClass";
option java_package = "com.google.goonami.proto";

// clients config
// most of these configs are in the `goonami.proto.configs.clients` namespace.
import "common/clients/httpcrawler/httpcrawler_client_config.proto";
import "common/clients/llm/llm_client_config.proto";
import "common/clients/nmap/nmap_client_config.proto";
import "tools/callbackserver/callbackserver_config.proto";

// portscan config
// these configs are in the `goonami.proto.configs.portscan` namespace.
import "plugins/portscan/httpscan/httpscan_portscan_config.proto";

// fingerprinters config
// these configs are in the `goonami.proto.configs.fingerprinters` namespace.
import "plugins/fingerprint/webidentity/webidentity_fp_config.proto";
import "plugins/detectors/templatedweakcredentials/templatedweakcredentials_config.proto";

message Config {
  GlobalConfig globalcfg = 1;
  ClientsConfig clients = 2;
  PluginsConfig plugins = 3;
  WorkflowConfiguration workflowcfg = 4;
}

// WorkflowConfiguration contains configuration to control which scanner,
// fingerprinters and detectors are run and in which order.
message WorkflowConfiguration {
  message ModuleFilter {
    // Require is matched against the list of registered modules and every match
    // is appended to the workflow to be executed. Supports regexes.
    // Note: Automatically embeds "^" and "$" around each entry.
    repeated string require = 1;

    // Once matches have been computed from require, they are filtered down
    // against this `ignore` entry.
    repeated string ignore = 2;
  }

  // Port scanner to use.
  optional string portscan = 1;

  // Fingerprinters to use (order dependent).
  optional ModuleFilter fingerprinters = 2;

  // Detectors to use (order dependent).
  optional ModuleFilter detectors = 3;
}

// GlobalConfig contains configuration that is used by the core engine and
// accessible by every plugin.
message GlobalConfig {
  message Performance {
    // Maximum number of concurrent requests.
    // Default: 5
    optional int32 max_concurrency = 1;

    // Time in second before a request is aborted. This applies to every HTTP
    // request and should also apply to most network requests generated by the
    // core engine.
    // Default: 10
    optional int32 timeout_per_request_seconds = 2;

    // Rate limiting for packets. This is a **best-effort** limit. Amongst other
    // things, it is applied to nmap. A value of 0 means no limit.
    // Default: 0 (no limit)
    optional int32 max_packets_per_second = 3;

    // Rate limiting for HTTP requests. A value of 0 means no limit.
    // Default: 0 (no limit)
    optional int32 max_http_requests_per_second = 4;
  }

  // Performance related configurations.
  optional Performance performance = 1;

  // Ports that the scanner will target.
  // Default: empty (scans every port)
  repeated uint32 ports_to_scan = 2;

  // User agent to use throughout the scan.
  // Default: empty
  optional string user_agent = 3;

  // HTTP client that will be used for all HTTP requests.
  // Default: "simpleclient"
  optional string http_client = 4;
}

// ClientsConfig contains configuration for clients.
message ClientsConfig {
  goonami.proto.configs.clients.NmapClientConfig nmap = 1;
  goonami.proto.configs.clients.HttpCrawlerClientConfig http_crawler = 2;
  goonami.proto.configs.clients.LlmClientConfig llm = 3;
  goonami.callbackserver.CallbackserverConfig callback_server = 4;
}

// PluginsConfig contains configuration for plugin.
message PluginsConfig {
  goonami.proto.configs.fingerprinters.WebIdentityFpConfig webidentity = 1;
  goonami.proto.configs.portscan.HttpScanPluginConfig httpscan = 2;
  goonami.proto.configs.detectors.TemplatedWeakCredentialsConfig templatedweakcredentials = 3;
}
