//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: callbackserver_config.proto

package callbackserver_config_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallbackEndpointMode int32

const (
	CallbackEndpointMode_MODE_UNSPECIFIED CallbackEndpointMode = 0
	// Goonami will start a local server to handle this endpoint.
	CallbackEndpointMode_MODE_START_LOCAL_SERVER CallbackEndpointMode = 1
	// Goonami will connect to a remote callback server for this endpoint.
	CallbackEndpointMode_MODE_USE_REMOTE_SERVER CallbackEndpointMode = 2
)

// Enum value maps for CallbackEndpointMode.
var (
	CallbackEndpointMode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_START_LOCAL_SERVER",
		2: "MODE_USE_REMOTE_SERVER",
	}
	CallbackEndpointMode_value = map[string]int32{
		"MODE_UNSPECIFIED":        0,
		"MODE_START_LOCAL_SERVER": 1,
		"MODE_USE_REMOTE_SERVER":  2,
	}
)

func (x CallbackEndpointMode) Enum() *CallbackEndpointMode {
	p := new(CallbackEndpointMode)
	*p = x
	return p
}

func (x CallbackEndpointMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallbackEndpointMode) Descriptor() protoreflect.EnumDescriptor {
	return file_callbackserver_config_proto_enumTypes[0].Descriptor()
}

func (CallbackEndpointMode) Type() protoreflect.EnumType {
	return &file_callbackserver_config_proto_enumTypes[0]
}

func (x CallbackEndpointMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type EndpointConfig struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Mode        CallbackEndpointMode   `protobuf:"varint,1,opt,name=mode,proto3,enum=goonami.callbackserver.CallbackEndpointMode"`
	xxx_hidden_PublicUri   string                 `protobuf:"bytes,2,opt,name=public_uri,json=publicUri,proto3"`
	xxx_hidden_BindAddress string                 `protobuf:"bytes,3,opt,name=bind_address,json=bindAddress,proto3"`
	xxx_hidden_BindPort    uint32                 `protobuf:"varint,4,opt,name=bind_port,json=bindPort,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EndpointConfig) Reset() {
	*x = EndpointConfig{}
	mi := &file_callbackserver_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointConfig) ProtoMessage() {}

func (x *EndpointConfig) ProtoReflect() protoreflect.Message {
	mi := &file_callbackserver_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EndpointConfig) GetMode() CallbackEndpointMode {
	if x != nil {
		return x.xxx_hidden_Mode
	}
	return CallbackEndpointMode_MODE_UNSPECIFIED
}

func (x *EndpointConfig) GetPublicUri() string {
	if x != nil {
		return x.xxx_hidden_PublicUri
	}
	return ""
}

func (x *EndpointConfig) GetBindAddress() string {
	if x != nil {
		return x.xxx_hidden_BindAddress
	}
	return ""
}

func (x *EndpointConfig) GetBindPort() uint32 {
	if x != nil {
		return x.xxx_hidden_BindPort
	}
	return 0
}

func (x *EndpointConfig) SetMode(v CallbackEndpointMode) {
	x.xxx_hidden_Mode = v
}

func (x *EndpointConfig) SetPublicUri(v string) {
	x.xxx_hidden_PublicUri = v
}

func (x *EndpointConfig) SetBindAddress(v string) {
	x.xxx_hidden_BindAddress = v
}

func (x *EndpointConfig) SetBindPort(v uint32) {
	x.xxx_hidden_BindPort = v
}

type EndpointConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The mode to use for the endpoint. Whether a local server should be started,
	// or if a remote server should be used.
	Mode CallbackEndpointMode
	// The FULL public URI used to reach the endpoint. For example:
	// http://127.0.0.1:8080 or http://cb.localhost.lan:8082 for HTTP interaction
	// or cb.localhost.lan:8082 for DNS interactions. This is usually what will
	// end up being used by the scanner.
	PublicUri string
	// Only used in MODE_START_LOCAL_SERVER mode. The address to bind to for a
	// local instance of the server.
	BindAddress string
	// Only used in MODE_START_LOCAL_SERVER mode. The port to bind to for a local
	// instance of the server.
	BindPort uint32
}

func (b0 EndpointConfig_builder) Build() *EndpointConfig {
	m0 := &EndpointConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Mode = b.Mode
	x.xxx_hidden_PublicUri = b.PublicUri
	x.xxx_hidden_BindAddress = b.BindAddress
	x.xxx_hidden_BindPort = b.BindPort
	return m0
}

type CallbackserverConfig struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HttpPollConfig         *EndpointConfig        `protobuf:"bytes,1,opt,name=http_poll_config,json=httpPollConfig,proto3"`
	xxx_hidden_HttpRecordConfig       *EndpointConfig        `protobuf:"bytes,2,opt,name=http_record_config,json=httpRecordConfig,proto3,oneof"`
	xxx_hidden_DnsRecordConfig        *EndpointConfig        `protobuf:"bytes,3,opt,name=dns_record_config,json=dnsRecordConfig,proto3,oneof"`
	xxx_hidden_InteractionTtlSeconds  uint32                 `protobuf:"varint,4,opt,name=interaction_ttl_seconds,json=interactionTtlSeconds,proto3"`
	xxx_hidden_CleanupIntervalSeconds uint32                 `protobuf:"varint,5,opt,name=cleanup_interval_seconds,json=cleanupIntervalSeconds,proto3"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *CallbackserverConfig) Reset() {
	*x = CallbackserverConfig{}
	mi := &file_callbackserver_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackserverConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackserverConfig) ProtoMessage() {}

func (x *CallbackserverConfig) ProtoReflect() protoreflect.Message {
	mi := &file_callbackserver_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CallbackserverConfig) GetHttpPollConfig() *EndpointConfig {
	if x != nil {
		return x.xxx_hidden_HttpPollConfig
	}
	return nil
}

func (x *CallbackserverConfig) GetHttpRecordConfig() *EndpointConfig {
	if x != nil {
		return x.xxx_hidden_HttpRecordConfig
	}
	return nil
}

func (x *CallbackserverConfig) GetDnsRecordConfig() *EndpointConfig {
	if x != nil {
		return x.xxx_hidden_DnsRecordConfig
	}
	return nil
}

func (x *CallbackserverConfig) GetInteractionTtlSeconds() uint32 {
	if x != nil {
		return x.xxx_hidden_InteractionTtlSeconds
	}
	return 0
}

func (x *CallbackserverConfig) GetCleanupIntervalSeconds() uint32 {
	if x != nil {
		return x.xxx_hidden_CleanupIntervalSeconds
	}
	return 0
}

func (x *CallbackserverConfig) SetHttpPollConfig(v *EndpointConfig) {
	x.xxx_hidden_HttpPollConfig = v
}

func (x *CallbackserverConfig) SetHttpRecordConfig(v *EndpointConfig) {
	x.xxx_hidden_HttpRecordConfig = v
}

func (x *CallbackserverConfig) SetDnsRecordConfig(v *EndpointConfig) {
	x.xxx_hidden_DnsRecordConfig = v
}

func (x *CallbackserverConfig) SetInteractionTtlSeconds(v uint32) {
	x.xxx_hidden_InteractionTtlSeconds = v
}

func (x *CallbackserverConfig) SetCleanupIntervalSeconds(v uint32) {
	x.xxx_hidden_CleanupIntervalSeconds = v
}

func (x *CallbackserverConfig) HasHttpPollConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HttpPollConfig != nil
}

func (x *CallbackserverConfig) HasHttpRecordConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HttpRecordConfig != nil
}

func (x *CallbackserverConfig) HasDnsRecordConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DnsRecordConfig != nil
}

func (x *CallbackserverConfig) ClearHttpPollConfig() {
	x.xxx_hidden_HttpPollConfig = nil
}

func (x *CallbackserverConfig) ClearHttpRecordConfig() {
	x.xxx_hidden_HttpRecordConfig = nil
}

func (x *CallbackserverConfig) ClearDnsRecordConfig() {
	x.xxx_hidden_DnsRecordConfig = nil
}

type CallbackserverConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The endpoint used to verify the presence of interactions.
	HttpPollConfig *EndpointConfig
	// The endpoint used to record HTTP interactions.
	HttpRecordConfig *EndpointConfig
	// The endpoint used to record DNS interactions.
	DnsRecordConfig *EndpointConfig
	// Time before interactions are invalidated.
	InteractionTtlSeconds uint32
	// The interval at which to run cleanup of expired interactions.
	CleanupIntervalSeconds uint32
}

func (b0 CallbackserverConfig_builder) Build() *CallbackserverConfig {
	m0 := &CallbackserverConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_HttpPollConfig = b.HttpPollConfig
	x.xxx_hidden_HttpRecordConfig = b.HttpRecordConfig
	x.xxx_hidden_DnsRecordConfig = b.DnsRecordConfig
	x.xxx_hidden_InteractionTtlSeconds = b.InteractionTtlSeconds
	x.xxx_hidden_CleanupIntervalSeconds = b.CleanupIntervalSeconds
	return m0
}

var File_callbackserver_config_proto protoreflect.FileDescriptor

const file_callbackserver_config_proto_rawDesc = "" +
	"\n" +
	"\x1bcallbackserver_config.proto\x12\x16goonami.callbackserver\"\xb1\x01\n" +
	"\x0eEndpointConfig\x12@\n" +
	"\x04mode\x18\x01 \x01(\x0e2,.goonami.callbackserver.CallbackEndpointModeR\x04mode\x12\x1d\n" +
	"\n" +
	"public_uri\x18\x02 \x01(\tR\tpublicUri\x12!\n" +
	"\fbind_address\x18\x03 \x01(\tR\vbindAddress\x12\x1b\n" +
	"\tbind_port\x18\x04 \x01(\rR\bbindPort\"\xbb\x03\n" +
	"\x14CallbackserverConfig\x12P\n" +
	"\x10http_poll_config\x18\x01 \x01(\v2&.goonami.callbackserver.EndpointConfigR\x0ehttpPollConfig\x12Y\n" +
	"\x12http_record_config\x18\x02 \x01(\v2&.goonami.callbackserver.EndpointConfigH\x00R\x10httpRecordConfig\x88\x01\x01\x12W\n" +
	"\x11dns_record_config\x18\x03 \x01(\v2&.goonami.callbackserver.EndpointConfigH\x01R\x0fdnsRecordConfig\x88\x01\x01\x126\n" +
	"\x17interaction_ttl_seconds\x18\x04 \x01(\rR\x15interactionTtlSeconds\x128\n" +
	"\x18cleanup_interval_seconds\x18\x05 \x01(\rR\x16cleanupIntervalSecondsB\x15\n" +
	"\x13_http_record_configB\x14\n" +
	"\x12_dns_record_config*e\n" +
	"\x14CallbackEndpointMode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MODE_START_LOCAL_SERVER\x10\x01\x12\x1a\n" +
	"\x16MODE_USE_REMOTE_SERVER\x10\x02B\xa2\x01\n" +
	"'com.google.goonami.callbackserver.protoB\x1eCallbackserverConfigOuterClassP\x01ZUgithub.com/google/goonami-scanner/tools/callbackserver/callbackserver_config_go_protob\x06proto3"

var file_callbackserver_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_callbackserver_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_callbackserver_config_proto_goTypes = []any{
	(CallbackEndpointMode)(0),    // 0: goonami.callbackserver.CallbackEndpointMode
	(*EndpointConfig)(nil),       // 1: goonami.callbackserver.EndpointConfig
	(*CallbackserverConfig)(nil), // 2: goonami.callbackserver.CallbackserverConfig
}
var file_callbackserver_config_proto_depIdxs = []int32{
	0, // 0: goonami.callbackserver.EndpointConfig.mode:type_name -> goonami.callbackserver.CallbackEndpointMode
	1, // 1: goonami.callbackserver.CallbackserverConfig.http_poll_config:type_name -> goonami.callbackserver.EndpointConfig
	1, // 2: goonami.callbackserver.CallbackserverConfig.http_record_config:type_name -> goonami.callbackserver.EndpointConfig
	1, // 3: goonami.callbackserver.CallbackserverConfig.dns_record_config:type_name -> goonami.callbackserver.EndpointConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_callbackserver_config_proto_init() }
func file_callbackserver_config_proto_init() {
	if File_callbackserver_config_proto != nil {
		return
	}
	file_callbackserver_config_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_callbackserver_config_proto_rawDesc), len(file_callbackserver_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_callbackserver_config_proto_goTypes,
		DependencyIndexes: file_callbackserver_config_proto_depIdxs,
		EnumInfos:         file_callbackserver_config_proto_enumTypes,
		MessageInfos:      file_callbackserver_config_proto_msgTypes,
	}.Build()
	File_callbackserver_config_proto = out.File
	file_callbackserver_config_proto_goTypes = nil
	file_callbackserver_config_proto_depIdxs = nil
}
