//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: httpscan_portscan_config.proto

package httpscan_portscan_config_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpScanPluginConfig struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InvalidExitCodes []int32                `protobuf:"varint,1,rep,packed,name=invalid_exit_codes,json=invalidExitCodes,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *HttpScanPluginConfig) Reset() {
	*x = HttpScanPluginConfig{}
	mi := &file_httpscan_portscan_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpScanPluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpScanPluginConfig) ProtoMessage() {}

func (x *HttpScanPluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_httpscan_portscan_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpScanPluginConfig) GetInvalidExitCodes() []int32 {
	if x != nil {
		return x.xxx_hidden_InvalidExitCodes
	}
	return nil
}

func (x *HttpScanPluginConfig) SetInvalidExitCodes(v []int32) {
	x.xxx_hidden_InvalidExitCodes = v
}

type HttpScanPluginConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// InvalidExitCodes represents HTTP code that signals that the port is closed.
	InvalidExitCodes []int32
}

func (b0 HttpScanPluginConfig_builder) Build() *HttpScanPluginConfig {
	m0 := &HttpScanPluginConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InvalidExitCodes = b.InvalidExitCodes
	return m0
}

var File_httpscan_portscan_config_proto protoreflect.FileDescriptor

const file_httpscan_portscan_config_proto_rawDesc = "" +
	"\n" +
	"\x1ehttpscan_portscan_config.proto\x12\x1egoonami.proto.configs.portscan\"D\n" +
	"\x14HttpScanPluginConfig\x12,\n" +
	"\x12invalid_exit_codes\x18\x01 \x03(\x05R\x10invalidExitCodesB\xac\x01\n" +
	")com.google.goonami.proto.configs.portscanB\x1eHttpScanPluginConfigOuterClassP\x01Z]github.com/google/goonami-scanner/plugins/portscan/httpscan/httpscan_portscan_config_go_protob\x06proto3"

var file_httpscan_portscan_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_httpscan_portscan_config_proto_goTypes = []any{
	(*HttpScanPluginConfig)(nil), // 0: goonami.proto.configs.portscan.HttpScanPluginConfig
}
var file_httpscan_portscan_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_httpscan_portscan_config_proto_init() }
func file_httpscan_portscan_config_proto_init() {
	if File_httpscan_portscan_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_httpscan_portscan_config_proto_rawDesc), len(file_httpscan_portscan_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_httpscan_portscan_config_proto_goTypes,
		DependencyIndexes: file_httpscan_portscan_config_proto_depIdxs,
		MessageInfos:      file_httpscan_portscan_config_proto_msgTypes,
	}.Build()
	File_httpscan_portscan_config_proto = out.File
	file_httpscan_portscan_config_proto_goTypes = nil
	file_httpscan_portscan_config_proto_depIdxs = nil
}
