//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: fingerprints.proto

package fingerprints_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The fingerprints data for a specific software.
type Fingerprints struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SoftwareIdentity *SoftwareIdentity      `protobuf:"bytes,1,opt,name=software_identity,json=softwareIdentity,proto3"`
	xxx_hidden_ContentHashes    *[]*ContentHash        `protobuf:"bytes,2,rep,name=content_hashes,json=contentHashes,proto3"`
	xxx_hidden_HashVersions     *[]*HashVersion        `protobuf:"bytes,3,rep,name=hash_versions,json=hashVersions,proto3"`
	xxx_hidden_PathVersions     *[]*PathVersion        `protobuf:"bytes,4,rep,name=path_versions,json=pathVersions,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Fingerprints) Reset() {
	*x = Fingerprints{}
	mi := &file_fingerprints_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fingerprints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fingerprints) ProtoMessage() {}

func (x *Fingerprints) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprints_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Fingerprints) GetSoftwareIdentity() *SoftwareIdentity {
	if x != nil {
		return x.xxx_hidden_SoftwareIdentity
	}
	return nil
}

func (x *Fingerprints) GetContentHashes() []*ContentHash {
	if x != nil {
		if x.xxx_hidden_ContentHashes != nil {
			return *x.xxx_hidden_ContentHashes
		}
	}
	return nil
}

func (x *Fingerprints) GetHashVersions() []*HashVersion {
	if x != nil {
		if x.xxx_hidden_HashVersions != nil {
			return *x.xxx_hidden_HashVersions
		}
	}
	return nil
}

func (x *Fingerprints) GetPathVersions() []*PathVersion {
	if x != nil {
		if x.xxx_hidden_PathVersions != nil {
			return *x.xxx_hidden_PathVersions
		}
	}
	return nil
}

func (x *Fingerprints) SetSoftwareIdentity(v *SoftwareIdentity) {
	x.xxx_hidden_SoftwareIdentity = v
}

func (x *Fingerprints) SetContentHashes(v []*ContentHash) {
	x.xxx_hidden_ContentHashes = &v
}

func (x *Fingerprints) SetHashVersions(v []*HashVersion) {
	x.xxx_hidden_HashVersions = &v
}

func (x *Fingerprints) SetPathVersions(v []*PathVersion) {
	x.xxx_hidden_PathVersions = &v
}

func (x *Fingerprints) HasSoftwareIdentity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SoftwareIdentity != nil
}

func (x *Fingerprints) ClearSoftwareIdentity() {
	x.xxx_hidden_SoftwareIdentity = nil
}

type Fingerprints_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The identity of the software.
	SoftwareIdentity *SoftwareIdentity
	// A list of web contents served by the application and their corresponding
	// content hashes.
	ContentHashes []*ContentHash
	// A list of web content hashes and their corresponding application versions.
	HashVersions []*HashVersion
	// A list of web content paths and their corresponding application versions.
	PathVersions []*PathVersion
}

func (b0 Fingerprints_builder) Build() *Fingerprints {
	m0 := &Fingerprints{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SoftwareIdentity = b.SoftwareIdentity
	x.xxx_hidden_ContentHashes = &b.ContentHashes
	x.xxx_hidden_HashVersions = &b.HashVersions
	x.xxx_hidden_PathVersions = &b.PathVersions
	return m0
}

type SoftwareIdentity struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Software string                 `protobuf:"bytes,1,opt,name=software,proto3"`
	xxx_hidden_Plugin   string                 `protobuf:"bytes,2,opt,name=plugin,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SoftwareIdentity) Reset() {
	*x = SoftwareIdentity{}
	mi := &file_fingerprints_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareIdentity) ProtoMessage() {}

func (x *SoftwareIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprints_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SoftwareIdentity) GetSoftware() string {
	if x != nil {
		return x.xxx_hidden_Software
	}
	return ""
}

func (x *SoftwareIdentity) GetPlugin() string {
	if x != nil {
		return x.xxx_hidden_Plugin
	}
	return ""
}

func (x *SoftwareIdentity) SetSoftware(v string) {
	x.xxx_hidden_Software = v
}

func (x *SoftwareIdentity) SetPlugin(v string) {
	x.xxx_hidden_Plugin = v
}

type SoftwareIdentity_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the software. Required.
	Software string
	// Name of the plugin for the software. Optional.
	Plugin string
}

func (b0 SoftwareIdentity_builder) Build() *SoftwareIdentity {
	m0 := &SoftwareIdentity{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Software = b.Software
	x.xxx_hidden_Plugin = b.Plugin
	return m0
}

// The hash data for a single web content served by the application.
type ContentHash struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContentPath string                 `protobuf:"bytes,1,opt,name=content_path,json=contentPath,proto3"`
	xxx_hidden_Hashes      *[]*Hash               `protobuf:"bytes,2,rep,name=hashes,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContentHash) Reset() {
	*x = ContentHash{}
	mi := &file_fingerprints_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentHash) ProtoMessage() {}

func (x *ContentHash) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprints_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContentHash) GetContentPath() string {
	if x != nil {
		return x.xxx_hidden_ContentPath
	}
	return ""
}

func (x *ContentHash) GetHashes() []*Hash {
	if x != nil {
		if x.xxx_hidden_Hashes != nil {
			return *x.xxx_hidden_Hashes
		}
	}
	return nil
}

func (x *ContentHash) SetContentPath(v string) {
	x.xxx_hidden_ContentPath = v
}

func (x *ContentHash) SetHashes(v []*Hash) {
	x.xxx_hidden_Hashes = &v
}

type ContentHash_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The path to the content. Required.
	ContentPath string
	// All the potential hashes for that content.
	Hashes []*Hash
}

func (b0 ContentHash_builder) Build() *ContentHash {
	m0 := &ContentHash{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ContentPath = b.ContentPath
	x.xxx_hidden_Hashes = &b.Hashes
	return m0
}

// The version information for a single web content hash.
type HashVersion struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Hash     *Hash                  `protobuf:"bytes,1,opt,name=hash,proto3"`
	xxx_hidden_Versions *[]*Version            `protobuf:"bytes,2,rep,name=versions,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HashVersion) Reset() {
	*x = HashVersion{}
	mi := &file_fingerprints_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashVersion) ProtoMessage() {}

func (x *HashVersion) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprints_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HashVersion) GetHash() *Hash {
	if x != nil {
		return x.xxx_hidden_Hash
	}
	return nil
}

func (x *HashVersion) GetVersions() []*Version {
	if x != nil {
		if x.xxx_hidden_Versions != nil {
			return *x.xxx_hidden_Versions
		}
	}
	return nil
}

func (x *HashVersion) SetHash(v *Hash) {
	x.xxx_hidden_Hash = v
}

func (x *HashVersion) SetVersions(v []*Version) {
	x.xxx_hidden_Versions = &v
}

func (x *HashVersion) HasHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Hash != nil
}

func (x *HashVersion) ClearHash() {
	x.xxx_hidden_Hash = nil
}

type HashVersion_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The hash of a web content.
	Hash *Hash
	// All the potential application versions for that content.
	Versions []*Version
}

func (b0 HashVersion_builder) Build() *HashVersion {
	m0 := &HashVersion{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Hash = b.Hash
	x.xxx_hidden_Versions = &b.Versions
	return m0
}

// The version information for a single web content path.
type PathVersion struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContentPath string                 `protobuf:"bytes,1,opt,name=content_path,json=contentPath,proto3"`
	xxx_hidden_Versions    *[]*Version            `protobuf:"bytes,2,rep,name=versions,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PathVersion) Reset() {
	*x = PathVersion{}
	mi := &file_fingerprints_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathVersion) ProtoMessage() {}

func (x *PathVersion) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprints_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PathVersion) GetContentPath() string {
	if x != nil {
		return x.xxx_hidden_ContentPath
	}
	return ""
}

func (x *PathVersion) GetVersions() []*Version {
	if x != nil {
		if x.xxx_hidden_Versions != nil {
			return *x.xxx_hidden_Versions
		}
	}
	return nil
}

func (x *PathVersion) SetContentPath(v string) {
	x.xxx_hidden_ContentPath = v
}

func (x *PathVersion) SetVersions(v []*Version) {
	x.xxx_hidden_Versions = &v
}

type PathVersion_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The path to the content.
	ContentPath string
	// All the potential application versions for that content path.
	Versions []*Version
}

func (b0 PathVersion_builder) Build() *PathVersion {
	m0 := &PathVersion{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ContentPath = b.ContentPath
	x.xxx_hidden_Versions = &b.Versions
	return m0
}

type Hash struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HexString string                 `protobuf:"bytes,1,opt,name=hex_string,json=hexString,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Hash) Reset() {
	*x = Hash{}
	mi := &file_fingerprints_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hash) ProtoMessage() {}

func (x *Hash) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprints_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Hash) GetHexString() string {
	if x != nil {
		return x.xxx_hidden_HexString
	}
	return ""
}

func (x *Hash) SetHexString(v string) {
	x.xxx_hidden_HexString = v
}

type Hash_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The hex representation of a hash value.
	HexString string
}

func (b0 Hash_builder) Build() *Hash {
	m0 := &Hash{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_HexString = b.HexString
	return m0
}

type Version struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FullName string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_fingerprints_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprints_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Version) GetFullName() string {
	if x != nil {
		return x.xxx_hidden_FullName
	}
	return ""
}

func (x *Version) SetFullName(v string) {
	x.xxx_hidden_FullName = v
}

type Version_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Human readable version string.
	FullName string
}

func (b0 Version_builder) Build() *Version {
	m0 := &Version{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FullName = b.FullName
	return m0
}

var File_fingerprints_proto protoreflect.FileDescriptor

const file_fingerprints_proto_rawDesc = "" +
	"\n" +
	"\x12fingerprints.proto\x12!goonami.proto.plugins.webidentity\"\xf1\x02\n" +
	"\fFingerprints\x12`\n" +
	"\x11software_identity\x18\x01 \x01(\v23.goonami.proto.plugins.webidentity.SoftwareIdentityR\x10softwareIdentity\x12U\n" +
	"\x0econtent_hashes\x18\x02 \x03(\v2..goonami.proto.plugins.webidentity.ContentHashR\rcontentHashes\x12S\n" +
	"\rhash_versions\x18\x03 \x03(\v2..goonami.proto.plugins.webidentity.HashVersionR\fhashVersions\x12S\n" +
	"\rpath_versions\x18\x04 \x03(\v2..goonami.proto.plugins.webidentity.PathVersionR\fpathVersions\"F\n" +
	"\x10SoftwareIdentity\x12\x1a\n" +
	"\bsoftware\x18\x01 \x01(\tR\bsoftware\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\"q\n" +
	"\vContentHash\x12!\n" +
	"\fcontent_path\x18\x01 \x01(\tR\vcontentPath\x12?\n" +
	"\x06hashes\x18\x02 \x03(\v2'.goonami.proto.plugins.webidentity.HashR\x06hashes\"\x92\x01\n" +
	"\vHashVersion\x12;\n" +
	"\x04hash\x18\x01 \x01(\v2'.goonami.proto.plugins.webidentity.HashR\x04hash\x12F\n" +
	"\bversions\x18\x02 \x03(\v2*.goonami.proto.plugins.webidentity.VersionR\bversions\"x\n" +
	"\vPathVersion\x12!\n" +
	"\fcontent_path\x18\x01 \x01(\tR\vcontentPath\x12F\n" +
	"\bversions\x18\x02 \x03(\v2*.goonami.proto.plugins.webidentity.VersionR\bversions\"%\n" +
	"\x04Hash\x12\x1d\n" +
	"\n" +
	"hex_string\x18\x01 \x01(\tR\thexString\"&\n" +
	"\aVersion\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullNameB\xa7\x01\n" +
	"2com.google.goonami.plugins.fingerprint.webidentityB\x16FingerprintsOuterClassP\x01ZWgithub.com/google/goonami-scanner/plugins/fingerprint/webidentity/fingerprints_go_protob\x06proto3"

var file_fingerprints_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_fingerprints_proto_goTypes = []any{
	(*Fingerprints)(nil),     // 0: goonami.proto.plugins.webidentity.Fingerprints
	(*SoftwareIdentity)(nil), // 1: goonami.proto.plugins.webidentity.SoftwareIdentity
	(*ContentHash)(nil),      // 2: goonami.proto.plugins.webidentity.ContentHash
	(*HashVersion)(nil),      // 3: goonami.proto.plugins.webidentity.HashVersion
	(*PathVersion)(nil),      // 4: goonami.proto.plugins.webidentity.PathVersion
	(*Hash)(nil),             // 5: goonami.proto.plugins.webidentity.Hash
	(*Version)(nil),          // 6: goonami.proto.plugins.webidentity.Version
}
var file_fingerprints_proto_depIdxs = []int32{
	1, // 0: goonami.proto.plugins.webidentity.Fingerprints.software_identity:type_name -> goonami.proto.plugins.webidentity.SoftwareIdentity
	2, // 1: goonami.proto.plugins.webidentity.Fingerprints.content_hashes:type_name -> goonami.proto.plugins.webidentity.ContentHash
	3, // 2: goonami.proto.plugins.webidentity.Fingerprints.hash_versions:type_name -> goonami.proto.plugins.webidentity.HashVersion
	4, // 3: goonami.proto.plugins.webidentity.Fingerprints.path_versions:type_name -> goonami.proto.plugins.webidentity.PathVersion
	5, // 4: goonami.proto.plugins.webidentity.ContentHash.hashes:type_name -> goonami.proto.plugins.webidentity.Hash
	5, // 5: goonami.proto.plugins.webidentity.HashVersion.hash:type_name -> goonami.proto.plugins.webidentity.Hash
	6, // 6: goonami.proto.plugins.webidentity.HashVersion.versions:type_name -> goonami.proto.plugins.webidentity.Version
	6, // 7: goonami.proto.plugins.webidentity.PathVersion.versions:type_name -> goonami.proto.plugins.webidentity.Version
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_fingerprints_proto_init() }
func file_fingerprints_proto_init() {
	if File_fingerprints_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fingerprints_proto_rawDesc), len(file_fingerprints_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fingerprints_proto_goTypes,
		DependencyIndexes: file_fingerprints_proto_depIdxs,
		MessageInfos:      file_fingerprints_proto_msgTypes,
	}.Build()
	File_fingerprints_proto = out.File
	file_fingerprints_proto_goTypes = nil
	file_fingerprints_proto_depIdxs = nil
}
