//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: templatedweakcredentials_config.proto

package templatedweakcredentials_config_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemplatedWeakCredentialsConfig struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MaxAttemptsPerService int32                  `protobuf:"varint,1,opt,name=max_attempts_per_service,json=maxAttemptsPerService,proto3,oneof"`
	xxx_hidden_UsernameFile          *string                `protobuf:"bytes,2,opt,name=username_file,json=usernameFile,proto3,oneof"`
	xxx_hidden_PasswordsFile         *string                `protobuf:"bytes,3,opt,name=passwords_file,json=passwordsFile,proto3,oneof"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *TemplatedWeakCredentialsConfig) Reset() {
	*x = TemplatedWeakCredentialsConfig{}
	mi := &file_templatedweakcredentials_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplatedWeakCredentialsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplatedWeakCredentialsConfig) ProtoMessage() {}

func (x *TemplatedWeakCredentialsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_templatedweakcredentials_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TemplatedWeakCredentialsConfig) GetMaxAttemptsPerService() int32 {
	if x != nil {
		return x.xxx_hidden_MaxAttemptsPerService
	}
	return 0
}

func (x *TemplatedWeakCredentialsConfig) GetUsernameFile() string {
	if x != nil {
		if x.xxx_hidden_UsernameFile != nil {
			return *x.xxx_hidden_UsernameFile
		}
		return ""
	}
	return ""
}

func (x *TemplatedWeakCredentialsConfig) GetPasswordsFile() string {
	if x != nil {
		if x.xxx_hidden_PasswordsFile != nil {
			return *x.xxx_hidden_PasswordsFile
		}
		return ""
	}
	return ""
}

func (x *TemplatedWeakCredentialsConfig) SetMaxAttemptsPerService(v int32) {
	x.xxx_hidden_MaxAttemptsPerService = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *TemplatedWeakCredentialsConfig) SetUsernameFile(v string) {
	x.xxx_hidden_UsernameFile = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *TemplatedWeakCredentialsConfig) SetPasswordsFile(v string) {
	x.xxx_hidden_PasswordsFile = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *TemplatedWeakCredentialsConfig) HasMaxAttemptsPerService() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TemplatedWeakCredentialsConfig) HasUsernameFile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TemplatedWeakCredentialsConfig) HasPasswordsFile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TemplatedWeakCredentialsConfig) ClearMaxAttemptsPerService() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MaxAttemptsPerService = 0
}

func (x *TemplatedWeakCredentialsConfig) ClearUsernameFile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_UsernameFile = nil
}

func (x *TemplatedWeakCredentialsConfig) ClearPasswordsFile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_PasswordsFile = nil
}

type TemplatedWeakCredentialsConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Maximum number of authentication attempts to make per service.
	MaxAttemptsPerService *int32
	// Path to a file containing a list of usernames to use for detection. Each
	// username should be on a separate line.
	UsernameFile *string
	// Path to a file containing a list of passwords to use for detection. Each
	// password should be on a separate line.
	PasswordsFile *string
}

func (b0 TemplatedWeakCredentialsConfig_builder) Build() *TemplatedWeakCredentialsConfig {
	m0 := &TemplatedWeakCredentialsConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MaxAttemptsPerService != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_MaxAttemptsPerService = *b.MaxAttemptsPerService
	}
	if b.UsernameFile != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_UsernameFile = b.UsernameFile
	}
	if b.PasswordsFile != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_PasswordsFile = b.PasswordsFile
	}
	return m0
}

var File_templatedweakcredentials_config_proto protoreflect.FileDescriptor

const file_templatedweakcredentials_config_proto_rawDesc = "" +
	"\n" +
	"%templatedweakcredentials_config.proto\x12\x1fgoonami.proto.configs.detectors\"\xf6\x01\n" +
	"\x1eTemplatedWeakCredentialsConfig\x12<\n" +
	"\x18max_attempts_per_service\x18\x01 \x01(\x05H\x00R\x15maxAttemptsPerService\x88\x01\x01\x12(\n" +
	"\rusername_file\x18\x02 \x01(\tH\x01R\fusernameFile\x88\x01\x01\x12*\n" +
	"\x0epasswords_file\x18\x03 \x01(\tH\x02R\rpasswordsFile\x88\x01\x01B\x1b\n" +
	"\x19_max_attempts_per_serviceB\x10\n" +
	"\x0e_username_fileB\x11\n" +
	"\x0f_passwords_fileB\xcf\x01\n" +
	"*com.google.goonami.proto.configs.detectorsB(TemplatedWeakCredentialsConfigOuterClassP\x01Zugithub.com/google/goonami-scanner/plugins/detectors/templatedweakcredentials/templatedweakcredentials_config_go_protob\x06proto3"

var file_templatedweakcredentials_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_templatedweakcredentials_config_proto_goTypes = []any{
	(*TemplatedWeakCredentialsConfig)(nil), // 0: goonami.proto.configs.detectors.TemplatedWeakCredentialsConfig
}
var file_templatedweakcredentials_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_templatedweakcredentials_config_proto_init() }
func file_templatedweakcredentials_config_proto_init() {
	if File_templatedweakcredentials_config_proto != nil {
		return
	}
	file_templatedweakcredentials_config_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_templatedweakcredentials_config_proto_rawDesc), len(file_templatedweakcredentials_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_templatedweakcredentials_config_proto_goTypes,
		DependencyIndexes: file_templatedweakcredentials_config_proto_depIdxs,
		MessageInfos:      file_templatedweakcredentials_config_proto_msgTypes,
	}.Build()
	File_templatedweakcredentials_config_proto = out.File
	file_templatedweakcredentials_config_proto_goTypes = nil
	file_templatedweakcredentials_config_proto_depIdxs = nil
}
