//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: config.proto

package config_go_proto

import (
	httpcrawler_client_config_go_proto "github.com/google/goonami-scanner/common/clients/httpcrawler/httpcrawler_client_config_go_proto"
	nmap_client_config_go_proto "github.com/google/goonami-scanner/common/clients/nmap/nmap_client_config_go_proto"
	webidentity_fp_config_go_proto "github.com/google/goonami-scanner/plugins/fingerprint/webidentity/webidentity_fp_config_go_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Globalcfg *GlobalConfig          `protobuf:"bytes,1,opt,name=globalcfg,proto3"`
	xxx_hidden_Clients   *ClientsConfig         `protobuf:"bytes,2,opt,name=clients,proto3"`
	xxx_hidden_Plugins   *PluginsConfig         `protobuf:"bytes,3,opt,name=plugins,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Config) GetGlobalcfg() *GlobalConfig {
	if x != nil {
		return x.xxx_hidden_Globalcfg
	}
	return nil
}

func (x *Config) GetClients() *ClientsConfig {
	if x != nil {
		return x.xxx_hidden_Clients
	}
	return nil
}

func (x *Config) GetPlugins() *PluginsConfig {
	if x != nil {
		return x.xxx_hidden_Plugins
	}
	return nil
}

func (x *Config) SetGlobalcfg(v *GlobalConfig) {
	x.xxx_hidden_Globalcfg = v
}

func (x *Config) SetClients(v *ClientsConfig) {
	x.xxx_hidden_Clients = v
}

func (x *Config) SetPlugins(v *PluginsConfig) {
	x.xxx_hidden_Plugins = v
}

func (x *Config) HasGlobalcfg() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Globalcfg != nil
}

func (x *Config) HasClients() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Clients != nil
}

func (x *Config) HasPlugins() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Plugins != nil
}

func (x *Config) ClearGlobalcfg() {
	x.xxx_hidden_Globalcfg = nil
}

func (x *Config) ClearClients() {
	x.xxx_hidden_Clients = nil
}

func (x *Config) ClearPlugins() {
	x.xxx_hidden_Plugins = nil
}

type Config_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Globalcfg *GlobalConfig
	Clients   *ClientsConfig
	Plugins   *PluginsConfig
}

func (b0 Config_builder) Build() *Config {
	m0 := &Config{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Globalcfg = b.Globalcfg
	x.xxx_hidden_Clients = b.Clients
	x.xxx_hidden_Plugins = b.Plugins
	return m0
}

// GlobalConfig contains configuration that is used by the core engine and
// accessible by every plugin.
type GlobalConfig struct {
	state                  protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Performance *GlobalConfig_Performance `protobuf:"bytes,1,opt,name=performance,proto3"`
	xxx_hidden_PortsToScan []uint32                  `protobuf:"varint,2,rep,packed,name=ports_to_scan,json=portsToScan,proto3"`
	xxx_hidden_UserAgent   string                    `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GlobalConfig) Reset() {
	*x = GlobalConfig{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfig) ProtoMessage() {}

func (x *GlobalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GlobalConfig) GetPerformance() *GlobalConfig_Performance {
	if x != nil {
		return x.xxx_hidden_Performance
	}
	return nil
}

func (x *GlobalConfig) GetPortsToScan() []uint32 {
	if x != nil {
		return x.xxx_hidden_PortsToScan
	}
	return nil
}

func (x *GlobalConfig) GetUserAgent() string {
	if x != nil {
		return x.xxx_hidden_UserAgent
	}
	return ""
}

func (x *GlobalConfig) SetPerformance(v *GlobalConfig_Performance) {
	x.xxx_hidden_Performance = v
}

func (x *GlobalConfig) SetPortsToScan(v []uint32) {
	x.xxx_hidden_PortsToScan = v
}

func (x *GlobalConfig) SetUserAgent(v string) {
	x.xxx_hidden_UserAgent = v
}

func (x *GlobalConfig) HasPerformance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Performance != nil
}

func (x *GlobalConfig) ClearPerformance() {
	x.xxx_hidden_Performance = nil
}

type GlobalConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Performance related configurations.
	Performance *GlobalConfig_Performance
	// Ports that the scanner will target.
	PortsToScan []uint32
	// User agent to use throughout the scan.
	UserAgent string
}

func (b0 GlobalConfig_builder) Build() *GlobalConfig {
	m0 := &GlobalConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Performance = b.Performance
	x.xxx_hidden_PortsToScan = b.PortsToScan
	x.xxx_hidden_UserAgent = b.UserAgent
	return m0
}

// ClientsConfig contains configuration for clients.
type ClientsConfig struct {
	state                  protoimpl.MessageState                                      `protogen:"opaque.v1"`
	xxx_hidden_Nmap        *nmap_client_config_go_proto.NmapClientConfig               `protobuf:"bytes,1,opt,name=nmap,proto3"`
	xxx_hidden_HttpCrawler *httpcrawler_client_config_go_proto.HttpCrawlerClientConfig `protobuf:"bytes,2,opt,name=http_crawler,json=httpCrawler,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ClientsConfig) Reset() {
	*x = ClientsConfig{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientsConfig) ProtoMessage() {}

func (x *ClientsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClientsConfig) GetNmap() *nmap_client_config_go_proto.NmapClientConfig {
	if x != nil {
		return x.xxx_hidden_Nmap
	}
	return nil
}

func (x *ClientsConfig) GetHttpCrawler() *httpcrawler_client_config_go_proto.HttpCrawlerClientConfig {
	if x != nil {
		return x.xxx_hidden_HttpCrawler
	}
	return nil
}

func (x *ClientsConfig) SetNmap(v *nmap_client_config_go_proto.NmapClientConfig) {
	x.xxx_hidden_Nmap = v
}

func (x *ClientsConfig) SetHttpCrawler(v *httpcrawler_client_config_go_proto.HttpCrawlerClientConfig) {
	x.xxx_hidden_HttpCrawler = v
}

func (x *ClientsConfig) HasNmap() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Nmap != nil
}

func (x *ClientsConfig) HasHttpCrawler() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HttpCrawler != nil
}

func (x *ClientsConfig) ClearNmap() {
	x.xxx_hidden_Nmap = nil
}

func (x *ClientsConfig) ClearHttpCrawler() {
	x.xxx_hidden_HttpCrawler = nil
}

type ClientsConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nmap        *nmap_client_config_go_proto.NmapClientConfig
	HttpCrawler *httpcrawler_client_config_go_proto.HttpCrawlerClientConfig
}

func (b0 ClientsConfig_builder) Build() *ClientsConfig {
	m0 := &ClientsConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nmap = b.Nmap
	x.xxx_hidden_HttpCrawler = b.HttpCrawler
	return m0
}

// PluginsConfig contains configuration for plugin.
type PluginsConfig struct {
	state                  protoimpl.MessageState                              `protogen:"opaque.v1"`
	xxx_hidden_Webidentity *webidentity_fp_config_go_proto.WebIdentityFpConfig `protobuf:"bytes,1,opt,name=webidentity,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PluginsConfig) Reset() {
	*x = PluginsConfig{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginsConfig) ProtoMessage() {}

func (x *PluginsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PluginsConfig) GetWebidentity() *webidentity_fp_config_go_proto.WebIdentityFpConfig {
	if x != nil {
		return x.xxx_hidden_Webidentity
	}
	return nil
}

func (x *PluginsConfig) SetWebidentity(v *webidentity_fp_config_go_proto.WebIdentityFpConfig) {
	x.xxx_hidden_Webidentity = v
}

func (x *PluginsConfig) HasWebidentity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Webidentity != nil
}

func (x *PluginsConfig) ClearWebidentity() {
	x.xxx_hidden_Webidentity = nil
}

type PluginsConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Webidentity *webidentity_fp_config_go_proto.WebIdentityFpConfig
}

func (b0 PluginsConfig_builder) Build() *PluginsConfig {
	m0 := &PluginsConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Webidentity = b.Webidentity
	return m0
}

type GlobalConfig_Performance struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MaxConcurrency           int32                  `protobuf:"varint,1,opt,name=max_concurrency,json=maxConcurrency,proto3"`
	xxx_hidden_TimeoutPerRequestSeconds int32                  `protobuf:"varint,2,opt,name=timeout_per_request_seconds,json=timeoutPerRequestSeconds,proto3"`
	xxx_hidden_MaxPacketsPerSecond      int32                  `protobuf:"varint,3,opt,name=max_packets_per_second,json=maxPacketsPerSecond,proto3"`
	xxx_hidden_MaxHttpRequestsPerSecond int32                  `protobuf:"varint,4,opt,name=max_http_requests_per_second,json=maxHttpRequestsPerSecond,proto3"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *GlobalConfig_Performance) Reset() {
	*x = GlobalConfig_Performance{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalConfig_Performance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfig_Performance) ProtoMessage() {}

func (x *GlobalConfig_Performance) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GlobalConfig_Performance) GetMaxConcurrency() int32 {
	if x != nil {
		return x.xxx_hidden_MaxConcurrency
	}
	return 0
}

func (x *GlobalConfig_Performance) GetTimeoutPerRequestSeconds() int32 {
	if x != nil {
		return x.xxx_hidden_TimeoutPerRequestSeconds
	}
	return 0
}

func (x *GlobalConfig_Performance) GetMaxPacketsPerSecond() int32 {
	if x != nil {
		return x.xxx_hidden_MaxPacketsPerSecond
	}
	return 0
}

func (x *GlobalConfig_Performance) GetMaxHttpRequestsPerSecond() int32 {
	if x != nil {
		return x.xxx_hidden_MaxHttpRequestsPerSecond
	}
	return 0
}

func (x *GlobalConfig_Performance) SetMaxConcurrency(v int32) {
	x.xxx_hidden_MaxConcurrency = v
}

func (x *GlobalConfig_Performance) SetTimeoutPerRequestSeconds(v int32) {
	x.xxx_hidden_TimeoutPerRequestSeconds = v
}

func (x *GlobalConfig_Performance) SetMaxPacketsPerSecond(v int32) {
	x.xxx_hidden_MaxPacketsPerSecond = v
}

func (x *GlobalConfig_Performance) SetMaxHttpRequestsPerSecond(v int32) {
	x.xxx_hidden_MaxHttpRequestsPerSecond = v
}

type GlobalConfig_Performance_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Maximum number of concurrent requests.
	MaxConcurrency int32
	// Time in second before a request is aborted. This applies to every HTTP
	// request and should also apply to most network requests generated by the
	// core engine.
	TimeoutPerRequestSeconds int32
	// Rate limiting for packets. This is a **best-effort** limit. Amongst other
	// things, it is applied to nmap. A value of 0 means no limit.
	MaxPacketsPerSecond int32
	// Rate limiting for HTTP requests. A value of 0 means no limit.
	MaxHttpRequestsPerSecond int32
}

func (b0 GlobalConfig_Performance_builder) Build() *GlobalConfig_Performance {
	m0 := &GlobalConfig_Performance{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MaxConcurrency = b.MaxConcurrency
	x.xxx_hidden_TimeoutPerRequestSeconds = b.TimeoutPerRequestSeconds
	x.xxx_hidden_MaxPacketsPerSecond = b.MaxPacketsPerSecond
	x.xxx_hidden_MaxHttpRequestsPerSecond = b.MaxHttpRequestsPerSecond
	return m0
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\rgoonami.proto\x1a:common/clients/httpcrawler/httpcrawler_client_config.proto\x1a,common/clients/nmap/nmap_client_config.proto\x1a;plugins/fingerprint/webidentity/webidentity_fp_config.proto\"\xb3\x01\n" +
	"\x06Config\x129\n" +
	"\tglobalcfg\x18\x01 \x01(\v2\x1b.goonami.proto.GlobalConfigR\tglobalcfg\x126\n" +
	"\aclients\x18\x02 \x01(\v2\x1c.goonami.proto.ClientsConfigR\aclients\x126\n" +
	"\aplugins\x18\x03 \x01(\v2\x1c.goonami.proto.PluginsConfigR\aplugins\"\x89\x03\n" +
	"\fGlobalConfig\x12I\n" +
	"\vperformance\x18\x01 \x01(\v2'.goonami.proto.GlobalConfig.PerformanceR\vperformance\x12\"\n" +
	"\rports_to_scan\x18\x02 \x03(\rR\vportsToScan\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x1a\xea\x01\n" +
	"\vPerformance\x12'\n" +
	"\x0fmax_concurrency\x18\x01 \x01(\x05R\x0emaxConcurrency\x12=\n" +
	"\x1btimeout_per_request_seconds\x18\x02 \x01(\x05R\x18timeoutPerRequestSeconds\x123\n" +
	"\x16max_packets_per_second\x18\x03 \x01(\x05R\x13maxPacketsPerSecond\x12>\n" +
	"\x1cmax_http_requests_per_second\x18\x04 \x01(\x05R\x18maxHttpRequestsPerSecond\"\xaf\x01\n" +
	"\rClientsConfig\x12C\n" +
	"\x04nmap\x18\x01 \x01(\v2/.goonami.proto.configs.clients.NmapClientConfigR\x04nmap\x12Y\n" +
	"\fhttp_crawler\x18\x02 \x01(\v26.goonami.proto.configs.clients.HttpCrawlerClientConfigR\vhttpCrawler\"l\n" +
	"\rPluginsConfig\x12[\n" +
	"\vwebidentity\x18\x01 \x01(\v29.goonami.proto.configs.fingerprinters.WebIdentityFpConfigR\vwebidentityBm\n" +
	"\x18com.google.goonami.protoB\x10ConfigOuterClassP\x01Z=github.com/google/goonami-scanner/core/config/config_go_protob\x06proto3"

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_config_proto_goTypes = []any{
	(*Config)(nil),                                       // 0: goonami.proto.Config
	(*GlobalConfig)(nil),                                 // 1: goonami.proto.GlobalConfig
	(*ClientsConfig)(nil),                                // 2: goonami.proto.ClientsConfig
	(*PluginsConfig)(nil),                                // 3: goonami.proto.PluginsConfig
	(*GlobalConfig_Performance)(nil),                     // 4: goonami.proto.GlobalConfig.Performance
	(*nmap_client_config_go_proto.NmapClientConfig)(nil), // 5: goonami.proto.configs.clients.NmapClientConfig
	(*httpcrawler_client_config_go_proto.HttpCrawlerClientConfig)(nil), // 6: goonami.proto.configs.clients.HttpCrawlerClientConfig
	(*webidentity_fp_config_go_proto.WebIdentityFpConfig)(nil),         // 7: goonami.proto.configs.fingerprinters.WebIdentityFpConfig
}
var file_config_proto_depIdxs = []int32{
	1, // 0: goonami.proto.Config.globalcfg:type_name -> goonami.proto.GlobalConfig
	2, // 1: goonami.proto.Config.clients:type_name -> goonami.proto.ClientsConfig
	3, // 2: goonami.proto.Config.plugins:type_name -> goonami.proto.PluginsConfig
	4, // 3: goonami.proto.GlobalConfig.performance:type_name -> goonami.proto.GlobalConfig.Performance
	5, // 4: goonami.proto.ClientsConfig.nmap:type_name -> goonami.proto.configs.clients.NmapClientConfig
	6, // 5: goonami.proto.ClientsConfig.http_crawler:type_name -> goonami.proto.configs.clients.HttpCrawlerClientConfig
	7, // 6: goonami.proto.PluginsConfig.webidentity:type_name -> goonami.proto.configs.fingerprinters.WebIdentityFpConfig
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
