/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto3";

package goonami.proto.configs.detectors;

option go_package = "github.com/google/goonami-scanner/plugins/detectors/templatedweakcredentials/templatedweakcredentials_config_go_proto";

option java_multiple_files = true;
option java_outer_classname = "TemplatedWeakCredentialsConfigOuterClass";
option java_package = "com.google.goonami.proto.configs.detectors";

message TemplatedWeakCredentialsConfig {
  // Maximum number of authentication attempts to make per service.
  optional int32 max_attempts_per_service = 1;

  // Path to a file containing a list of usernames to use for detection. Each
  // username should be on a separate line.
  optional string username_file = 2;

  // Path to a file containing a list of passwords to use for detection. Each
  // password should be on a separate line.
  optional string passwords_file = 3;
}
