//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: scan_metrics.proto

package scan_metrics_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScanMetrics is the aggregated telemetry of a single scan, written next to the
// scan results at the end of a run.
type ScanMetrics struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Series  *[]*Series             `protobuf:"bytes,1,rep,name=series,proto3"`
	xxx_hidden_Dropped *[]*DroppedSeries      `protobuf:"bytes,2,rep,name=dropped,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScanMetrics) Reset() {
	*x = ScanMetrics{}
	mi := &file_scan_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanMetrics) ProtoMessage() {}

func (x *ScanMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_scan_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScanMetrics) GetSeries() []*Series {
	if x != nil {
		if x.xxx_hidden_Series != nil {
			return *x.xxx_hidden_Series
		}
	}
	return nil
}

func (x *ScanMetrics) GetDropped() []*DroppedSeries {
	if x != nil {
		if x.xxx_hidden_Dropped != nil {
			return *x.xxx_hidden_Dropped
		}
	}
	return nil
}

func (x *ScanMetrics) SetSeries(v []*Series) {
	x.xxx_hidden_Series = &v
}

func (x *ScanMetrics) SetDropped(v []*DroppedSeries) {
	x.xxx_hidden_Dropped = &v
}

type ScanMetrics_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The collected series, ordered by name then labels.
	Series []*Series
	// Metrics that exceeded their series cap. A non-empty list means a label was
	// unbounded and the corresponding series are incomplete.
	Dropped []*DroppedSeries
}

func (b0 ScanMetrics_builder) Build() *ScanMetrics {
	m0 := &ScanMetrics{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Series = &b.Series
	x.xxx_hidden_Dropped = &b.Dropped
	return m0
}

// Label is one dimension of a series.
type Label struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   string                 `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_Value string                 `protobuf:"bytes,2,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_scan_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_scan_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Label) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *Label) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *Label) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type Label_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   string
	Value string
}

func (b0 Label_builder) Build() *Label {
	m0 := &Label{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	return m0
}

// Distribution summarizes the samples of a distribution series.
type Distribution struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Count int64                  `protobuf:"varint,1,opt,name=count,proto3"`
	xxx_hidden_Sum   float64                `protobuf:"fixed64,2,opt,name=sum,proto3"`
	xxx_hidden_Min   float64                `protobuf:"fixed64,3,opt,name=min,proto3"`
	xxx_hidden_Max   float64                `protobuf:"fixed64,4,opt,name=max,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Distribution) Reset() {
	*x = Distribution{}
	mi := &file_scan_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution) ProtoMessage() {}

func (x *Distribution) ProtoReflect() protoreflect.Message {
	mi := &file_scan_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Distribution) GetCount() int64 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *Distribution) GetSum() float64 {
	if x != nil {
		return x.xxx_hidden_Sum
	}
	return 0
}

func (x *Distribution) GetMin() float64 {
	if x != nil {
		return x.xxx_hidden_Min
	}
	return 0
}

func (x *Distribution) GetMax() float64 {
	if x != nil {
		return x.xxx_hidden_Max
	}
	return 0
}

func (x *Distribution) SetCount(v int64) {
	x.xxx_hidden_Count = v
}

func (x *Distribution) SetSum(v float64) {
	x.xxx_hidden_Sum = v
}

func (x *Distribution) SetMin(v float64) {
	x.xxx_hidden_Min = v
}

func (x *Distribution) SetMax(v float64) {
	x.xxx_hidden_Max = v
}

type Distribution_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Number of samples.
	Count int64
	// Total of every sample.
	Sum float64
	// Smallest sample.
	Min float64
	// Largest sample.
	Max float64
}

func (b0 Distribution_builder) Build() *Distribution {
	m0 := &Distribution{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Count = b.Count
	x.xxx_hidden_Sum = b.Sum
	x.xxx_hidden_Min = b.Min
	x.xxx_hidden_Max = b.Max
	return m0
}

// Series is a single metric with a single combination of labels.
type Series struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name   string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Labels *[]*Label              `protobuf:"bytes,2,rep,name=labels,proto3"`
	xxx_hidden_Value  isSeries_Value         `protobuf_oneof:"value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_scan_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_scan_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Series) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Series) GetLabels() []*Label {
	if x != nil {
		if x.xxx_hidden_Labels != nil {
			return *x.xxx_hidden_Labels
		}
	}
	return nil
}

func (x *Series) GetCounter() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*series_Counter); ok {
			return x.Counter
		}
	}
	return 0
}

func (x *Series) GetDistribution() *Distribution {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*series_Distribution); ok {
			return x.Distribution
		}
	}
	return nil
}

func (x *Series) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Series) SetLabels(v []*Label) {
	x.xxx_hidden_Labels = &v
}

func (x *Series) SetCounter(v int64) {
	x.xxx_hidden_Value = &series_Counter{v}
}

func (x *Series) SetDistribution(v *Distribution) {
	if v == nil {
		x.xxx_hidden_Value = nil
		return
	}
	x.xxx_hidden_Value = &series_Distribution{v}
}

func (x *Series) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *Series) HasCounter() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*series_Counter)
	return ok
}

func (x *Series) HasDistribution() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*series_Distribution)
	return ok
}

func (x *Series) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *Series) ClearCounter() {
	if _, ok := x.xxx_hidden_Value.(*series_Counter); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *Series) ClearDistribution() {
	if _, ok := x.xxx_hidden_Value.(*series_Distribution); ok {
		x.xxx_hidden_Value = nil
	}
}

const Series_Value_not_set_case case_Series_Value = 0
const Series_Counter_case case_Series_Value = 3
const Series_Distribution_case case_Series_Value = 4

func (x *Series) WhichValue() case_Series_Value {
	if x == nil {
		return Series_Value_not_set_case
	}
	switch x.xxx_hidden_Value.(type) {
	case *series_Counter:
		return Series_Counter_case
	case *series_Distribution:
		return Series_Distribution_case
	default:
		return Series_Value_not_set_case
	}
}

type Series_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the metric, e.g. "module/duration".
	Name string
	// Dimensions of this series.
	Labels []*Label
	// Fields of oneof xxx_hidden_Value:
	// Total of a counter.
	Counter *int64
	// Summary of a distribution.
	Distribution *Distribution
	// -- end of xxx_hidden_Value
}

func (b0 Series_builder) Build() *Series {
	m0 := &Series{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Labels = &b.Labels
	if b.Counter != nil {
		x.xxx_hidden_Value = &series_Counter{*b.Counter}
	}
	if b.Distribution != nil {
		x.xxx_hidden_Value = &series_Distribution{b.Distribution}
	}
	return m0
}

type case_Series_Value protoreflect.FieldNumber

func (x case_Series_Value) String() string {
	md := file_scan_metrics_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isSeries_Value interface {
	isSeries_Value()
}

type series_Counter struct {
	// Total of a counter.
	Counter int64 `protobuf:"varint,3,opt,name=counter,proto3,oneof"`
}

type series_Distribution struct {
	// Summary of a distribution.
	Distribution *Distribution `protobuf:"bytes,4,opt,name=distribution,proto3,oneof"`
}

func (*series_Counter) isSeries_Value() {}

func (*series_Distribution) isSeries_Value() {}

// DroppedSeries reports observations lost to a metric's series cap.
type DroppedSeries struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metric       string                 `protobuf:"bytes,1,opt,name=metric,proto3"`
	xxx_hidden_Observations int64                  `protobuf:"varint,2,opt,name=observations,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DroppedSeries) Reset() {
	*x = DroppedSeries{}
	mi := &file_scan_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroppedSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroppedSeries) ProtoMessage() {}

func (x *DroppedSeries) ProtoReflect() protoreflect.Message {
	mi := &file_scan_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DroppedSeries) GetMetric() string {
	if x != nil {
		return x.xxx_hidden_Metric
	}
	return ""
}

func (x *DroppedSeries) GetObservations() int64 {
	if x != nil {
		return x.xxx_hidden_Observations
	}
	return 0
}

func (x *DroppedSeries) SetMetric(v string) {
	x.xxx_hidden_Metric = v
}

func (x *DroppedSeries) SetObservations(v int64) {
	x.xxx_hidden_Observations = v
}

type DroppedSeries_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the metric that reached its cap.
	Metric string
	// Number of observations dropped.
	Observations int64
}

func (b0 DroppedSeries_builder) Build() *DroppedSeries {
	m0 := &DroppedSeries{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metric = b.Metric
	x.xxx_hidden_Observations = b.Observations
	return m0
}

var File_scan_metrics_proto protoreflect.FileDescriptor

const file_scan_metrics_proto_rawDesc = "" +
	"\n" +
	"\x12scan_metrics.proto\x12\x15goonami.proto.metrics\"\x84\x01\n" +
	"\vScanMetrics\x125\n" +
	"\x06series\x18\x01 \x03(\v2\x1d.goonami.proto.metrics.SeriesR\x06series\x12>\n" +
	"\adropped\x18\x02 \x03(\v2$.goonami.proto.metrics.DroppedSeriesR\adropped\"/\n" +
	"\x05Label\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"Z\n" +
	"\fDistribution\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x10\n" +
	"\x03sum\x18\x02 \x01(\x01R\x03sum\x12\x10\n" +
	"\x03min\x18\x03 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x01R\x03max\"\xc2\x01\n" +
	"\x06Series\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x06labels\x18\x02 \x03(\v2\x1c.goonami.proto.metrics.LabelR\x06labels\x12\x1a\n" +
	"\acounter\x18\x03 \x01(\x03H\x00R\acounter\x12I\n" +
	"\fdistribution\x18\x04 \x01(\v2#.goonami.proto.metrics.DistributionH\x00R\fdistributionB\a\n" +
	"\x05value\"K\n" +
	"\rDroppedSeries\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\"\n" +
	"\fobservations\x18\x02 \x01(\x03R\fobservationsB\x81\x01\n" +
	" com.google.goonami.proto.metricsB\x15ScanMetricsOuterClassP\x01ZDgithub.com/google/goonami-scanner/core/metrics/scan_metrics_go_protob\x06proto3"

var file_scan_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_scan_metrics_proto_goTypes = []any{
	(*ScanMetrics)(nil),   // 0: goonami.proto.metrics.ScanMetrics
	(*Label)(nil),         // 1: goonami.proto.metrics.Label
	(*Distribution)(nil),  // 2: goonami.proto.metrics.Distribution
	(*Series)(nil),        // 3: goonami.proto.metrics.Series
	(*DroppedSeries)(nil), // 4: goonami.proto.metrics.DroppedSeries
}
var file_scan_metrics_proto_depIdxs = []int32{
	3, // 0: goonami.proto.metrics.ScanMetrics.series:type_name -> goonami.proto.metrics.Series
	4, // 1: goonami.proto.metrics.ScanMetrics.dropped:type_name -> goonami.proto.metrics.DroppedSeries
	1, // 2: goonami.proto.metrics.Series.labels:type_name -> goonami.proto.metrics.Label
	2, // 3: goonami.proto.metrics.Series.distribution:type_name -> goonami.proto.metrics.Distribution
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_scan_metrics_proto_init() }
func file_scan_metrics_proto_init() {
	if File_scan_metrics_proto != nil {
		return
	}
	file_scan_metrics_proto_msgTypes[3].OneofWrappers = []any{
		(*series_Counter)(nil),
		(*series_Distribution)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scan_metrics_proto_rawDesc), len(file_scan_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scan_metrics_proto_goTypes,
		DependencyIndexes: file_scan_metrics_proto_depIdxs,
		MessageInfos:      file_scan_metrics_proto_msgTypes,
	}.Build()
	File_scan_metrics_proto = out.File
	file_scan_metrics_proto_goTypes = nil
	file_scan_metrics_proto_depIdxs = nil
}
