//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: polling.proto

package polling_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The polling result message
type PollingResult struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HasDnsInteraction  bool                   `protobuf:"varint,1,opt,name=has_dns_interaction,json=hasDnsInteraction,proto3"`
	xxx_hidden_HasHttpInteraction bool                   `protobuf:"varint,2,opt,name=has_http_interaction,json=hasHttpInteraction,proto3"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *PollingResult) Reset() {
	*x = PollingResult{}
	mi := &file_polling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollingResult) ProtoMessage() {}

func (x *PollingResult) ProtoReflect() protoreflect.Message {
	mi := &file_polling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PollingResult) GetHasDnsInteraction() bool {
	if x != nil {
		return x.xxx_hidden_HasDnsInteraction
	}
	return false
}

func (x *PollingResult) GetHasHttpInteraction() bool {
	if x != nil {
		return x.xxx_hidden_HasHttpInteraction
	}
	return false
}

func (x *PollingResult) SetHasDnsInteraction(v bool) {
	x.xxx_hidden_HasDnsInteraction = v
}

func (x *PollingResult) SetHasHttpInteraction(v bool) {
	x.xxx_hidden_HasHttpInteraction = v
}

type PollingResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether or not the scan target has DNS interaction with TCS.
	HasDnsInteraction bool
	// Whether or not the scan target has HTTP interaction with TCS.
	HasHttpInteraction bool
}

func (b0 PollingResult_builder) Build() *PollingResult {
	m0 := &PollingResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_HasDnsInteraction = b.HasDnsInteraction
	x.xxx_hidden_HasHttpInteraction = b.HasHttpInteraction
	return m0
}

var File_polling_proto protoreflect.FileDescriptor

const file_polling_proto_rawDesc = "" +
	"\n" +
	"\rpolling.proto\x12$goonami.proto.clients.callbackserver\"q\n" +
	"\rPollingResult\x12.\n" +
	"\x13has_dns_interaction\x18\x01 \x01(\bR\x11hasDnsInteraction\x120\n" +
	"\x14has_http_interaction\x18\x02 \x01(\bR\x12hasHttpInteractionB\x94\x01\n" +
	"/com.google.goonami.proto.clients.callbackserverB\rPollingProtosP\x01ZPgithub.com/google/goonami-scanner/common/clients/callbackserver/polling_go_protob\x06proto3"

var file_polling_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_polling_proto_goTypes = []any{
	(*PollingResult)(nil), // 0: goonami.proto.clients.callbackserver.PollingResult
}
var file_polling_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_polling_proto_init() }
func file_polling_proto_init() {
	if File_polling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polling_proto_rawDesc), len(file_polling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polling_proto_goTypes,
		DependencyIndexes: file_polling_proto_depIdxs,
		MessageInfos:      file_polling_proto_msgTypes,
	}.Build()
	File_polling_proto = out.File
	file_polling_proto_goTypes = nil
	file_polling_proto_depIdxs = nil
}
