//
// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: httpcrawler_client_config.proto

package httpcrawler_client_config_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpCrawlerClientConfig_ScopePolicy int32

const (
	HttpCrawlerClientConfig_SCOPE_POLICY_UNSPECIFIED HttpCrawlerClientConfig_ScopePolicy = 0
	// Only use the scope defined in this config.
	HttpCrawlerClientConfig_SCOPE_POLICY_CONFIG_ONLY HttpCrawlerClientConfig_ScopePolicy = 1
	// Use the scope defined in this config and derive a new scope for each of
	// the initial URLs sent to the crawler.
	HttpCrawlerClientConfig_SCOPE_POLICY_EXPAND HttpCrawlerClientConfig_ScopePolicy = 2
)

// Enum value maps for HttpCrawlerClientConfig_ScopePolicy.
var (
	HttpCrawlerClientConfig_ScopePolicy_name = map[int32]string{
		0: "SCOPE_POLICY_UNSPECIFIED",
		1: "SCOPE_POLICY_CONFIG_ONLY",
		2: "SCOPE_POLICY_EXPAND",
	}
	HttpCrawlerClientConfig_ScopePolicy_value = map[string]int32{
		"SCOPE_POLICY_UNSPECIFIED": 0,
		"SCOPE_POLICY_CONFIG_ONLY": 1,
		"SCOPE_POLICY_EXPAND":      2,
	}
)

func (x HttpCrawlerClientConfig_ScopePolicy) Enum() *HttpCrawlerClientConfig_ScopePolicy {
	p := new(HttpCrawlerClientConfig_ScopePolicy)
	*p = x
	return p
}

func (x HttpCrawlerClientConfig_ScopePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpCrawlerClientConfig_ScopePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_httpcrawler_client_config_proto_enumTypes[0].Descriptor()
}

func (HttpCrawlerClientConfig_ScopePolicy) Type() protoreflect.EnumType {
	return &file_httpcrawler_client_config_proto_enumTypes[0]
}

func (x HttpCrawlerClientConfig_ScopePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type HttpCrawlerClientConfig struct {
	state                       protoimpl.MessageState              `protogen:"opaque.v1"`
	xxx_hidden_MaxConcurrency   int32                               `protobuf:"varint,1,opt,name=max_concurrency,json=maxConcurrency,proto3"`
	xxx_hidden_MaxPageSizeBytes int32                               `protobuf:"varint,2,opt,name=max_page_size_bytes,json=maxPageSizeBytes,proto3"`
	xxx_hidden_MaxDepth         int32                               `protobuf:"varint,3,opt,name=max_depth,json=maxDepth,proto3"`
	xxx_hidden_MaxRequests      int32                               `protobuf:"varint,4,opt,name=max_requests,json=maxRequests,proto3"`
	xxx_hidden_Exclusions       []string                            `protobuf:"bytes,5,rep,name=exclusions,proto3"`
	xxx_hidden_ScopePolicy      HttpCrawlerClientConfig_ScopePolicy `protobuf:"varint,6,opt,name=scope_policy,json=scopePolicy,proto3,enum=goonami.proto.configs.clients.HttpCrawlerClientConfig_ScopePolicy"`
	xxx_hidden_Scopes           *[]*HttpCrawlerClientConfig_Scope   `protobuf:"bytes,7,rep,name=scopes,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *HttpCrawlerClientConfig) Reset() {
	*x = HttpCrawlerClientConfig{}
	mi := &file_httpcrawler_client_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpCrawlerClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpCrawlerClientConfig) ProtoMessage() {}

func (x *HttpCrawlerClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_httpcrawler_client_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpCrawlerClientConfig) GetMaxConcurrency() int32 {
	if x != nil {
		return x.xxx_hidden_MaxConcurrency
	}
	return 0
}

func (x *HttpCrawlerClientConfig) GetMaxPageSizeBytes() int32 {
	if x != nil {
		return x.xxx_hidden_MaxPageSizeBytes
	}
	return 0
}

func (x *HttpCrawlerClientConfig) GetMaxDepth() int32 {
	if x != nil {
		return x.xxx_hidden_MaxDepth
	}
	return 0
}

func (x *HttpCrawlerClientConfig) GetMaxRequests() int32 {
	if x != nil {
		return x.xxx_hidden_MaxRequests
	}
	return 0
}

func (x *HttpCrawlerClientConfig) GetExclusions() []string {
	if x != nil {
		return x.xxx_hidden_Exclusions
	}
	return nil
}

func (x *HttpCrawlerClientConfig) GetScopePolicy() HttpCrawlerClientConfig_ScopePolicy {
	if x != nil {
		return x.xxx_hidden_ScopePolicy
	}
	return HttpCrawlerClientConfig_SCOPE_POLICY_UNSPECIFIED
}

func (x *HttpCrawlerClientConfig) GetScopes() []*HttpCrawlerClientConfig_Scope {
	if x != nil {
		if x.xxx_hidden_Scopes != nil {
			return *x.xxx_hidden_Scopes
		}
	}
	return nil
}

func (x *HttpCrawlerClientConfig) SetMaxConcurrency(v int32) {
	x.xxx_hidden_MaxConcurrency = v
}

func (x *HttpCrawlerClientConfig) SetMaxPageSizeBytes(v int32) {
	x.xxx_hidden_MaxPageSizeBytes = v
}

func (x *HttpCrawlerClientConfig) SetMaxDepth(v int32) {
	x.xxx_hidden_MaxDepth = v
}

func (x *HttpCrawlerClientConfig) SetMaxRequests(v int32) {
	x.xxx_hidden_MaxRequests = v
}

func (x *HttpCrawlerClientConfig) SetExclusions(v []string) {
	x.xxx_hidden_Exclusions = v
}

func (x *HttpCrawlerClientConfig) SetScopePolicy(v HttpCrawlerClientConfig_ScopePolicy) {
	x.xxx_hidden_ScopePolicy = v
}

func (x *HttpCrawlerClientConfig) SetScopes(v []*HttpCrawlerClientConfig_Scope) {
	x.xxx_hidden_Scopes = &v
}

type HttpCrawlerClientConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The maximum number of concurrent requests to be made. Note that this
	// concurrency is a product of the core engine concurrency: if the core engine
	// has a concurrency of 2 and this one 5, the scale can go up to 10.
	MaxConcurrency int32
	// The maximum size (in Bytes) of a page. Pages larger than this size will be
	// dropped by the crawler. This field has to be set, a value of 0 will read
	// nothing. Note that is can drastically increase memory usage: each crawler
	// goroutine will have its own buffer. So for example, if the total number of
	// goroutines is 100 and this size is 1MB, that is already 100MB of memory.
	MaxPageSizeBytes int32
	// The maximum depth to crawl. The depth is defined by the number of links
	// followed in a chain.
	MaxDepth int32
	// Maximum number of requests to be made. This is a hard limit on the number
	// of requests made by the crawler. It is enforced at the client level, it
	// means that its count will be shared between calls to Crawl(). In other
	// words, it is shared between targets crawled.
	MaxRequests int32
	// Paths to exclude from the crawl. This is a list of regular expressions that
	// will be matched against the URL of a page before it is crawled.
	Exclusions []string
	// Policy to use for the scope. If unspecified, SCOPE_POLICY_EXPAND will be
	// used.
	ScopePolicy HttpCrawlerClientConfig_ScopePolicy
	// The scopes to crawl. How this scopes are used is defined by the scope
	// policy.
	Scopes []*HttpCrawlerClientConfig_Scope
}

func (b0 HttpCrawlerClientConfig_builder) Build() *HttpCrawlerClientConfig {
	m0 := &HttpCrawlerClientConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MaxConcurrency = b.MaxConcurrency
	x.xxx_hidden_MaxPageSizeBytes = b.MaxPageSizeBytes
	x.xxx_hidden_MaxDepth = b.MaxDepth
	x.xxx_hidden_MaxRequests = b.MaxRequests
	x.xxx_hidden_Exclusions = b.Exclusions
	x.xxx_hidden_ScopePolicy = b.ScopePolicy
	x.xxx_hidden_Scopes = &b.Scopes
	return m0
}

// Note that this is a copy of the Scope from Tsunami. It was copied because
// of its simplicity and the challenge of resolving remote proto definitions.
// See https://github.com/google/tsunami-security-scanner/blob/master/proto/web_crawl.proto
type HttpCrawlerClientConfig_Scope struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Domain string                 `protobuf:"bytes,1,opt,name=domain,proto3"`
	xxx_hidden_Path   string                 `protobuf:"bytes,2,opt,name=path,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HttpCrawlerClientConfig_Scope) Reset() {
	*x = HttpCrawlerClientConfig_Scope{}
	mi := &file_httpcrawler_client_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpCrawlerClientConfig_Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpCrawlerClientConfig_Scope) ProtoMessage() {}

func (x *HttpCrawlerClientConfig_Scope) ProtoReflect() protoreflect.Message {
	mi := &file_httpcrawler_client_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpCrawlerClientConfig_Scope) GetDomain() string {
	if x != nil {
		return x.xxx_hidden_Domain
	}
	return ""
}

func (x *HttpCrawlerClientConfig_Scope) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *HttpCrawlerClientConfig_Scope) SetDomain(v string) {
	x.xxx_hidden_Domain = v
}

func (x *HttpCrawlerClientConfig_Scope) SetPath(v string) {
	x.xxx_hidden_Path = v
}

type HttpCrawlerClientConfig_Scope_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The domain to crawl.
	Domain string
	// The subpath (a directory) to crawl. Expected to be slash terminated.
	Path string
}

func (b0 HttpCrawlerClientConfig_Scope_builder) Build() *HttpCrawlerClientConfig_Scope {
	m0 := &HttpCrawlerClientConfig_Scope{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Domain = b.Domain
	x.xxx_hidden_Path = b.Path
	return m0
}

var File_httpcrawler_client_config_proto protoreflect.FileDescriptor

const file_httpcrawler_client_config_proto_rawDesc = "" +
	"\n" +
	"\x1fhttpcrawler_client_config.proto\x12\x1dgoonami.proto.configs.clients\"\xa7\x04\n" +
	"\x17HttpCrawlerClientConfig\x12'\n" +
	"\x0fmax_concurrency\x18\x01 \x01(\x05R\x0emaxConcurrency\x12-\n" +
	"\x13max_page_size_bytes\x18\x02 \x01(\x05R\x10maxPageSizeBytes\x12\x1b\n" +
	"\tmax_depth\x18\x03 \x01(\x05R\bmaxDepth\x12!\n" +
	"\fmax_requests\x18\x04 \x01(\x05R\vmaxRequests\x12\x1e\n" +
	"\n" +
	"exclusions\x18\x05 \x03(\tR\n" +
	"exclusions\x12e\n" +
	"\fscope_policy\x18\x06 \x01(\x0e2B.goonami.proto.configs.clients.HttpCrawlerClientConfig.ScopePolicyR\vscopePolicy\x12T\n" +
	"\x06scopes\x18\a \x03(\v2<.goonami.proto.configs.clients.HttpCrawlerClientConfig.ScopeR\x06scopes\x1a3\n" +
	"\x05Scope\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"b\n" +
	"\vScopePolicy\x12\x1c\n" +
	"\x18SCOPE_POLICY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SCOPE_POLICY_CONFIG_ONLY\x10\x01\x12\x17\n" +
	"\x13SCOPE_POLICY_EXPAND\x10\x02B\xb0\x01\n" +
	"(com.google.goonami.proto.configs.clientsB!HttpCrawlerClientConfigOuterClassP\x01Z_github.com/google/goonami-scanner/common/clients/httpcrawler/httpcrawler_client_config_go_protob\x06proto3"

var file_httpcrawler_client_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_httpcrawler_client_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_httpcrawler_client_config_proto_goTypes = []any{
	(HttpCrawlerClientConfig_ScopePolicy)(0), // 0: goonami.proto.configs.clients.HttpCrawlerClientConfig.ScopePolicy
	(*HttpCrawlerClientConfig)(nil),          // 1: goonami.proto.configs.clients.HttpCrawlerClientConfig
	(*HttpCrawlerClientConfig_Scope)(nil),    // 2: goonami.proto.configs.clients.HttpCrawlerClientConfig.Scope
}
var file_httpcrawler_client_config_proto_depIdxs = []int32{
	0, // 0: goonami.proto.configs.clients.HttpCrawlerClientConfig.scope_policy:type_name -> goonami.proto.configs.clients.HttpCrawlerClientConfig.ScopePolicy
	2, // 1: goonami.proto.configs.clients.HttpCrawlerClientConfig.scopes:type_name -> goonami.proto.configs.clients.HttpCrawlerClientConfig.Scope
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_httpcrawler_client_config_proto_init() }
func file_httpcrawler_client_config_proto_init() {
	if File_httpcrawler_client_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_httpcrawler_client_config_proto_rawDesc), len(file_httpcrawler_client_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_httpcrawler_client_config_proto_goTypes,
		DependencyIndexes: file_httpcrawler_client_config_proto_depIdxs,
		EnumInfos:         file_httpcrawler_client_config_proto_enumTypes,
		MessageInfos:      file_httpcrawler_client_config_proto_msgTypes,
	}.Build()
	File_httpcrawler_client_config_proto = out.File
	file_httpcrawler_client_config_proto_goTypes = nil
	file_httpcrawler_client_config_proto_depIdxs = nil
}
