//
// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: webidentity_fp_config.proto

package webidentity_fp_config_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebIdentityFpConfig struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_WriteHtmlToFile          bool                   `protobuf:"varint,1,opt,name=write_html_to_file,json=writeHtmlToFile,proto3"`
	xxx_hidden_MaximumFileSizeBytes     int64                  `protobuf:"varint,2,opt,name=maximum_file_size_bytes,json=maximumFileSizeBytes,proto3"`
	xxx_hidden_MaximumStorageSpaceBytes int64                  `protobuf:"varint,3,opt,name=maximum_storage_space_bytes,json=maximumStorageSpaceBytes,proto3"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *WebIdentityFpConfig) Reset() {
	*x = WebIdentityFpConfig{}
	mi := &file_webidentity_fp_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebIdentityFpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebIdentityFpConfig) ProtoMessage() {}

func (x *WebIdentityFpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_webidentity_fp_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WebIdentityFpConfig) GetWriteHtmlToFile() bool {
	if x != nil {
		return x.xxx_hidden_WriteHtmlToFile
	}
	return false
}

func (x *WebIdentityFpConfig) GetMaximumFileSizeBytes() int64 {
	if x != nil {
		return x.xxx_hidden_MaximumFileSizeBytes
	}
	return 0
}

func (x *WebIdentityFpConfig) GetMaximumStorageSpaceBytes() int64 {
	if x != nil {
		return x.xxx_hidden_MaximumStorageSpaceBytes
	}
	return 0
}

func (x *WebIdentityFpConfig) SetWriteHtmlToFile(v bool) {
	x.xxx_hidden_WriteHtmlToFile = v
}

func (x *WebIdentityFpConfig) SetMaximumFileSizeBytes(v int64) {
	x.xxx_hidden_MaximumFileSizeBytes = v
}

func (x *WebIdentityFpConfig) SetMaximumStorageSpaceBytes(v int64) {
	x.xxx_hidden_MaximumStorageSpaceBytes = v
}

type WebIdentityFpConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether to write the HTML response to a file as we crawl the web service.
	WriteHtmlToFile bool
	// If storing the HTML response, this is the maximum size of one file.
	MaximumFileSizeBytes int64
	// If storing the HTML response, this is the maximum amount of storage space
	// to use.
	MaximumStorageSpaceBytes int64
}

func (b0 WebIdentityFpConfig_builder) Build() *WebIdentityFpConfig {
	m0 := &WebIdentityFpConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_WriteHtmlToFile = b.WriteHtmlToFile
	x.xxx_hidden_MaximumFileSizeBytes = b.MaximumFileSizeBytes
	x.xxx_hidden_MaximumStorageSpaceBytes = b.MaximumStorageSpaceBytes
	return m0
}

var File_webidentity_fp_config_proto protoreflect.FileDescriptor

const file_webidentity_fp_config_proto_rawDesc = "" +
	"\n" +
	"\x1bwebidentity_fp_config.proto\x12$goonami.proto.configs.fingerprinters\"\xb8\x01\n" +
	"\x13WebIdentityFpConfig\x12+\n" +
	"\x12write_html_to_file\x18\x01 \x01(\bR\x0fwriteHtmlToFile\x125\n" +
	"\x17maximum_file_size_bytes\x18\x02 \x01(\x03R\x14maximumFileSizeBytes\x12=\n" +
	"\x1bmaximum_storage_space_bytes\x18\x03 \x01(\x03R\x18maximumStorageSpaceBytesB\xb4\x01\n" +
	"/com.google.goonami.proto.configs.fingerprintersB\x1dWebIdentityFpConfigOuterClassP\x01Z`github.com/google/goonami-scanner/plugins/fingerprint/webidentity/webidentity_fp_config_go_protob\x06proto3"

var file_webidentity_fp_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_webidentity_fp_config_proto_goTypes = []any{
	(*WebIdentityFpConfig)(nil), // 0: goonami.proto.configs.fingerprinters.WebIdentityFpConfig
}
var file_webidentity_fp_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_webidentity_fp_config_proto_init() }
func file_webidentity_fp_config_proto_init() {
	if File_webidentity_fp_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webidentity_fp_config_proto_rawDesc), len(file_webidentity_fp_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webidentity_fp_config_proto_goTypes,
		DependencyIndexes: file_webidentity_fp_config_proto_depIdxs,
		MessageInfos:      file_webidentity_fp_config_proto_msgTypes,
	}.Build()
	File_webidentity_fp_config_proto = out.File
	file_webidentity_fp_config_proto_goTypes = nil
	file_webidentity_fp_config_proto_depIdxs = nil
}
