//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: callbackserver_tool_config.proto

package callbackserver_tool_config_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallbackserverToolConfig struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecordConfig           *RecordConfig          `protobuf:"bytes,1,opt,name=record_config,json=recordConfig,proto3"`
	xxx_hidden_PollConfig             *PollConfig            `protobuf:"bytes,2,opt,name=poll_config,json=pollConfig,proto3"`
	xxx_hidden_InteractionTtlSeconds  uint32                 `protobuf:"varint,3,opt,name=interaction_ttl_seconds,json=interactionTtlSeconds,proto3"`
	xxx_hidden_CleanupIntervalSeconds uint32                 `protobuf:"varint,4,opt,name=cleanup_interval_seconds,json=cleanupIntervalSeconds,proto3"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *CallbackserverToolConfig) Reset() {
	*x = CallbackserverToolConfig{}
	mi := &file_callbackserver_tool_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackserverToolConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackserverToolConfig) ProtoMessage() {}

func (x *CallbackserverToolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_callbackserver_tool_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CallbackserverToolConfig) GetRecordConfig() *RecordConfig {
	if x != nil {
		return x.xxx_hidden_RecordConfig
	}
	return nil
}

func (x *CallbackserverToolConfig) GetPollConfig() *PollConfig {
	if x != nil {
		return x.xxx_hidden_PollConfig
	}
	return nil
}

func (x *CallbackserverToolConfig) GetInteractionTtlSeconds() uint32 {
	if x != nil {
		return x.xxx_hidden_InteractionTtlSeconds
	}
	return 0
}

func (x *CallbackserverToolConfig) GetCleanupIntervalSeconds() uint32 {
	if x != nil {
		return x.xxx_hidden_CleanupIntervalSeconds
	}
	return 0
}

func (x *CallbackserverToolConfig) SetRecordConfig(v *RecordConfig) {
	x.xxx_hidden_RecordConfig = v
}

func (x *CallbackserverToolConfig) SetPollConfig(v *PollConfig) {
	x.xxx_hidden_PollConfig = v
}

func (x *CallbackserverToolConfig) SetInteractionTtlSeconds(v uint32) {
	x.xxx_hidden_InteractionTtlSeconds = v
}

func (x *CallbackserverToolConfig) SetCleanupIntervalSeconds(v uint32) {
	x.xxx_hidden_CleanupIntervalSeconds = v
}

func (x *CallbackserverToolConfig) HasRecordConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RecordConfig != nil
}

func (x *CallbackserverToolConfig) HasPollConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PollConfig != nil
}

func (x *CallbackserverToolConfig) ClearRecordConfig() {
	x.xxx_hidden_RecordConfig = nil
}

func (x *CallbackserverToolConfig) ClearPollConfig() {
	x.xxx_hidden_PollConfig = nil
}

type CallbackserverToolConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The configuration for the recording server. This is the server used to
	// record interactions within detectors.
	RecordConfig *RecordConfig
	// The configuration for the polling server. It is used to verify that a
	// vulnerability triggered.
	PollConfig *PollConfig
	// Time before cleaning a given interaction in seconds.
	InteractionTtlSeconds uint32
	// The interval at which to run cleanup of expired interactions.
	CleanupIntervalSeconds uint32
}

func (b0 CallbackserverToolConfig_builder) Build() *CallbackserverToolConfig {
	m0 := &CallbackserverToolConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RecordConfig = b.RecordConfig
	x.xxx_hidden_PollConfig = b.PollConfig
	x.xxx_hidden_InteractionTtlSeconds = b.InteractionTtlSeconds
	x.xxx_hidden_CleanupIntervalSeconds = b.CleanupIntervalSeconds
	return m0
}

type RecordConfig struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Address string                 `protobuf:"bytes,1,opt,name=address,proto3"`
	xxx_hidden_Port    uint32                 `protobuf:"varint,2,opt,name=port,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecordConfig) Reset() {
	*x = RecordConfig{}
	mi := &file_callbackserver_tool_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordConfig) ProtoMessage() {}

func (x *RecordConfig) ProtoReflect() protoreflect.Message {
	mi := &file_callbackserver_tool_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecordConfig) GetAddress() string {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return ""
}

func (x *RecordConfig) GetPort() uint32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *RecordConfig) SetAddress(v string) {
	x.xxx_hidden_Address = v
}

func (x *RecordConfig) SetPort(v uint32) {
	x.xxx_hidden_Port = v
}

type RecordConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The address to listen for incoming connections.
	Address string
	// The port to listen for incoming connections.
	Port uint32
}

func (b0 RecordConfig_builder) Build() *RecordConfig {
	m0 := &RecordConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Address = b.Address
	x.xxx_hidden_Port = b.Port
	return m0
}

type PollConfig struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Address string                 `protobuf:"bytes,1,opt,name=address,proto3"`
	xxx_hidden_Port    uint32                 `protobuf:"varint,2,opt,name=port,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PollConfig) Reset() {
	*x = PollConfig{}
	mi := &file_callbackserver_tool_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollConfig) ProtoMessage() {}

func (x *PollConfig) ProtoReflect() protoreflect.Message {
	mi := &file_callbackserver_tool_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PollConfig) GetAddress() string {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return ""
}

func (x *PollConfig) GetPort() uint32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *PollConfig) SetAddress(v string) {
	x.xxx_hidden_Address = v
}

func (x *PollConfig) SetPort(v uint32) {
	x.xxx_hidden_Port = v
}

type PollConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The address to listen for incoming connections.
	Address string
	// The port to listen for incoming connections.
	Port uint32
}

func (b0 PollConfig_builder) Build() *PollConfig {
	m0 := &PollConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Address = b.Address
	x.xxx_hidden_Port = b.Port
	return m0
}

var File_callbackserver_tool_config_proto protoreflect.FileDescriptor

const file_callbackserver_tool_config_proto_rawDesc = "" +
	"\n" +
	" callbackserver_tool_config.proto\x12\x16goonami.callbackserver\"\x9c\x02\n" +
	"\x18CallbackserverToolConfig\x12I\n" +
	"\rrecord_config\x18\x01 \x01(\v2$.goonami.callbackserver.RecordConfigR\frecordConfig\x12C\n" +
	"\vpoll_config\x18\x02 \x01(\v2\".goonami.callbackserver.PollConfigR\n" +
	"pollConfig\x126\n" +
	"\x17interaction_ttl_seconds\x18\x03 \x01(\rR\x15interactionTtlSeconds\x128\n" +
	"\x18cleanup_interval_seconds\x18\x04 \x01(\rR\x16cleanupIntervalSeconds\"<\n" +
	"\fRecordConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\":\n" +
	"\n" +
	"PollConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04portB\xab\x01\n" +
	"'com.google.goonami.callbackserver.protoB\"CallbackserverToolConfigOuterClassP\x01ZZgithub.com/google/goonami-scanner/tools/callbackserver/callbackserver_tool_config_go_protob\x06proto3"

var file_callbackserver_tool_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_callbackserver_tool_config_proto_goTypes = []any{
	(*CallbackserverToolConfig)(nil), // 0: goonami.callbackserver.CallbackserverToolConfig
	(*RecordConfig)(nil),             // 1: goonami.callbackserver.RecordConfig
	(*PollConfig)(nil),               // 2: goonami.callbackserver.PollConfig
}
var file_callbackserver_tool_config_proto_depIdxs = []int32{
	1, // 0: goonami.callbackserver.CallbackserverToolConfig.record_config:type_name -> goonami.callbackserver.RecordConfig
	2, // 1: goonami.callbackserver.CallbackserverToolConfig.poll_config:type_name -> goonami.callbackserver.PollConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_callbackserver_tool_config_proto_init() }
func file_callbackserver_tool_config_proto_init() {
	if File_callbackserver_tool_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_callbackserver_tool_config_proto_rawDesc), len(file_callbackserver_tool_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_callbackserver_tool_config_proto_goTypes,
		DependencyIndexes: file_callbackserver_tool_config_proto_depIdxs,
		MessageInfos:      file_callbackserver_tool_config_proto_msgTypes,
	}.Build()
	File_callbackserver_tool_config_proto = out.File
	file_callbackserver_tool_config_proto_goTypes = nil
	file_callbackserver_tool_config_proto_depIdxs = nil
}
