//
// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: nmap_client_config.proto

package nmap_client_config_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NmapClientConfig_Technique int32

const (
	NmapClientConfig_UNKNOWN NmapClientConfig_Technique = 0
	// Perform a connect scan. Option: -sT
	NmapClientConfig_CONNECT NmapClientConfig_Technique = 1
	// Perform a UDP scan. Option: -sU
	NmapClientConfig_UDP NmapClientConfig_Technique = 2
)

// Enum value maps for NmapClientConfig_Technique.
var (
	NmapClientConfig_Technique_name = map[int32]string{
		0: "UNKNOWN",
		1: "CONNECT",
		2: "UDP",
	}
	NmapClientConfig_Technique_value = map[string]int32{
		"UNKNOWN": 0,
		"CONNECT": 1,
		"UDP":     2,
	}
)

func (x NmapClientConfig_Technique) Enum() *NmapClientConfig_Technique {
	p := new(NmapClientConfig_Technique)
	*p = x
	return p
}

func (x NmapClientConfig_Technique) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NmapClientConfig_Technique) Descriptor() protoreflect.EnumDescriptor {
	return file_nmap_client_config_proto_enumTypes[0].Descriptor()
}

func (NmapClientConfig_Technique) Type() protoreflect.EnumType {
	return &file_nmap_client_config_proto_enumTypes[0]
}

func (x NmapClientConfig_Technique) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type NmapClientConfig struct {
	state                                 protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_BinaryPath                 string                     `protobuf:"bytes,1,opt,name=binary_path,json=binaryPath,proto3"`
	xxx_hidden_TimeoutSeconds             int32                      `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3"`
	xxx_hidden_ScanTechnique              NmapClientConfig_Technique `protobuf:"varint,3,opt,name=scan_technique,json=scanTechnique,proto3,enum=goonami.proto.configs.clients.NmapClientConfig_Technique"`
	xxx_hidden_ScanIntensity              uint32                     `protobuf:"varint,4,opt,name=scan_intensity,json=scanIntensity,proto3"`
	xxx_hidden_EnableHostDiscovery        bool                       `protobuf:"varint,5,opt,name=enable_host_discovery,json=enableHostDiscovery,proto3"`
	xxx_hidden_EnableVersionDetection     bool                       `protobuf:"varint,6,opt,name=enable_version_detection,json=enableVersionDetection,proto3"`
	xxx_hidden_VersionIntensity           uint32                     `protobuf:"varint,7,opt,name=version_intensity,json=versionIntensity,proto3"`
	xxx_hidden_EnableHttpMethodsDetection bool                       `protobuf:"varint,8,opt,name=enable_http_methods_detection,json=enableHttpMethodsDetection,proto3"`
	xxx_hidden_EnableSslDetection         bool                       `protobuf:"varint,9,opt,name=enable_ssl_detection,json=enableSslDetection,proto3"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *NmapClientConfig) Reset() {
	*x = NmapClientConfig{}
	mi := &file_nmap_client_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NmapClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NmapClientConfig) ProtoMessage() {}

func (x *NmapClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_nmap_client_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NmapClientConfig) GetBinaryPath() string {
	if x != nil {
		return x.xxx_hidden_BinaryPath
	}
	return ""
}

func (x *NmapClientConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.xxx_hidden_TimeoutSeconds
	}
	return 0
}

func (x *NmapClientConfig) GetScanTechnique() NmapClientConfig_Technique {
	if x != nil {
		return x.xxx_hidden_ScanTechnique
	}
	return NmapClientConfig_UNKNOWN
}

func (x *NmapClientConfig) GetScanIntensity() uint32 {
	if x != nil {
		return x.xxx_hidden_ScanIntensity
	}
	return 0
}

func (x *NmapClientConfig) GetEnableHostDiscovery() bool {
	if x != nil {
		return x.xxx_hidden_EnableHostDiscovery
	}
	return false
}

func (x *NmapClientConfig) GetEnableVersionDetection() bool {
	if x != nil {
		return x.xxx_hidden_EnableVersionDetection
	}
	return false
}

func (x *NmapClientConfig) GetVersionIntensity() uint32 {
	if x != nil {
		return x.xxx_hidden_VersionIntensity
	}
	return 0
}

func (x *NmapClientConfig) GetEnableHttpMethodsDetection() bool {
	if x != nil {
		return x.xxx_hidden_EnableHttpMethodsDetection
	}
	return false
}

func (x *NmapClientConfig) GetEnableSslDetection() bool {
	if x != nil {
		return x.xxx_hidden_EnableSslDetection
	}
	return false
}

func (x *NmapClientConfig) SetBinaryPath(v string) {
	x.xxx_hidden_BinaryPath = v
}

func (x *NmapClientConfig) SetTimeoutSeconds(v int32) {
	x.xxx_hidden_TimeoutSeconds = v
}

func (x *NmapClientConfig) SetScanTechnique(v NmapClientConfig_Technique) {
	x.xxx_hidden_ScanTechnique = v
}

func (x *NmapClientConfig) SetScanIntensity(v uint32) {
	x.xxx_hidden_ScanIntensity = v
}

func (x *NmapClientConfig) SetEnableHostDiscovery(v bool) {
	x.xxx_hidden_EnableHostDiscovery = v
}

func (x *NmapClientConfig) SetEnableVersionDetection(v bool) {
	x.xxx_hidden_EnableVersionDetection = v
}

func (x *NmapClientConfig) SetVersionIntensity(v uint32) {
	x.xxx_hidden_VersionIntensity = v
}

func (x *NmapClientConfig) SetEnableHttpMethodsDetection(v bool) {
	x.xxx_hidden_EnableHttpMethodsDetection = v
}

func (x *NmapClientConfig) SetEnableSslDetection(v bool) {
	x.xxx_hidden_EnableSslDetection = v
}

type NmapClientConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// (Optional) Path to the nmap binary. If empty, the client will try to use
	// the nmap binary found in the current PATH.
	BinaryPath string
	// Maximum time nmap is allowed to run. This option is handled by the client
	// library and enforced on the nmap binary.
	TimeoutSeconds int32
	// The scan technique (SYN, CONNECT, ...) (e.g. -sS, -sT)
	ScanTechnique NmapClientConfig_Technique
	// Intensity (from 1 to 5) of the scan (-T1 to -T5).
	ScanIntensity uint32
	// Host discovery; when disabled: -Pn
	EnableHostDiscovery bool
	// version detection; -sV
	EnableVersionDetection bool
	// --version-intensity, ignored if enable_version_detection is false
	VersionIntensity uint32
	// scripts: Enable HTTP methods detection (--script http-methods).
	EnableHttpMethodsDetection bool
	// scripts: Enable SSL detection (--script ssl-cert,ssl-enum-ciphers)
	EnableSslDetection bool
}

func (b0 NmapClientConfig_builder) Build() *NmapClientConfig {
	m0 := &NmapClientConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BinaryPath = b.BinaryPath
	x.xxx_hidden_TimeoutSeconds = b.TimeoutSeconds
	x.xxx_hidden_ScanTechnique = b.ScanTechnique
	x.xxx_hidden_ScanIntensity = b.ScanIntensity
	x.xxx_hidden_EnableHostDiscovery = b.EnableHostDiscovery
	x.xxx_hidden_EnableVersionDetection = b.EnableVersionDetection
	x.xxx_hidden_VersionIntensity = b.VersionIntensity
	x.xxx_hidden_EnableHttpMethodsDetection = b.EnableHttpMethodsDetection
	x.xxx_hidden_EnableSslDetection = b.EnableSslDetection
	return m0
}

var File_nmap_client_config_proto protoreflect.FileDescriptor

const file_nmap_client_config_proto_rawDesc = "" +
	"\n" +
	"\x18nmap_client_config.proto\x12\x1dgoonami.proto.configs.clients\"\xa5\x04\n" +
	"\x10NmapClientConfig\x12\x1f\n" +
	"\vbinary_path\x18\x01 \x01(\tR\n" +
	"binaryPath\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\x12`\n" +
	"\x0escan_technique\x18\x03 \x01(\x0e29.goonami.proto.configs.clients.NmapClientConfig.TechniqueR\rscanTechnique\x12%\n" +
	"\x0escan_intensity\x18\x04 \x01(\rR\rscanIntensity\x122\n" +
	"\x15enable_host_discovery\x18\x05 \x01(\bR\x13enableHostDiscovery\x128\n" +
	"\x18enable_version_detection\x18\x06 \x01(\bR\x16enableVersionDetection\x12+\n" +
	"\x11version_intensity\x18\a \x01(\rR\x10versionIntensity\x12A\n" +
	"\x1denable_http_methods_detection\x18\b \x01(\bR\x1aenableHttpMethodsDetection\x120\n" +
	"\x14enable_ssl_detection\x18\t \x01(\bR\x12enableSslDetection\".\n" +
	"\tTechnique\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aCONNECT\x10\x01\x12\a\n" +
	"\x03UDP\x10\x02B\x9b\x01\n" +
	"(com.google.goonami.proto.configs.clientsB\x1aNmapClientConfigOuterClassP\x01ZQgithub.com/google/goonami-scanner/common/clients/nmap/nmap_client_config_go_protob\x06proto3"

var file_nmap_client_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nmap_client_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nmap_client_config_proto_goTypes = []any{
	(NmapClientConfig_Technique)(0), // 0: goonami.proto.configs.clients.NmapClientConfig.Technique
	(*NmapClientConfig)(nil),        // 1: goonami.proto.configs.clients.NmapClientConfig
}
var file_nmap_client_config_proto_depIdxs = []int32{
	0, // 0: goonami.proto.configs.clients.NmapClientConfig.scan_technique:type_name -> goonami.proto.configs.clients.NmapClientConfig.Technique
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nmap_client_config_proto_init() }
func file_nmap_client_config_proto_init() {
	if File_nmap_client_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nmap_client_config_proto_rawDesc), len(file_nmap_client_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nmap_client_config_proto_goTypes,
		DependencyIndexes: file_nmap_client_config_proto_depIdxs,
		EnumInfos:         file_nmap_client_config_proto_enumTypes,
		MessageInfos:      file_nmap_client_config_proto_msgTypes,
	}.Build()
	File_nmap_client_config_proto = out.File
	file_nmap_client_config_proto_goTypes = nil
	file_nmap_client_config_proto_depIdxs = nil
}
