//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: llm_client_config.proto

package llm_client_config_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LlmClientConfig struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TimeoutPerRequestSeconds int32                  `protobuf:"varint,1,opt,name=timeout_per_request_seconds,json=timeoutPerRequestSeconds,proto3,oneof"`
	xxx_hidden_MaxAttempts              int32                  `protobuf:"varint,2,opt,name=max_attempts,json=maxAttempts,proto3,oneof"`
	xxx_hidden_RetryDelaySeconds        int32                  `protobuf:"varint,3,opt,name=retry_delay_seconds,json=retryDelaySeconds,proto3,oneof"`
	xxx_hidden_Tools                    *ToolConfig            `protobuf:"bytes,4,opt,name=tools,proto3,oneof"`
	xxx_hidden_LiteModel                *string                `protobuf:"bytes,5,opt,name=lite_model,json=liteModel,proto3,oneof"`
	xxx_hidden_FastModel                *string                `protobuf:"bytes,6,opt,name=fast_model,json=fastModel,proto3,oneof"`
	xxx_hidden_ProModel                 *string                `protobuf:"bytes,7,opt,name=pro_model,json=proModel,proto3,oneof"`
	XXX_raceDetectHookData              protoimpl.RaceDetectHookData
	XXX_presence                        [1]uint32
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *LlmClientConfig) Reset() {
	*x = LlmClientConfig{}
	mi := &file_llm_client_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LlmClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LlmClientConfig) ProtoMessage() {}

func (x *LlmClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_llm_client_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LlmClientConfig) GetTimeoutPerRequestSeconds() int32 {
	if x != nil {
		return x.xxx_hidden_TimeoutPerRequestSeconds
	}
	return 0
}

func (x *LlmClientConfig) GetMaxAttempts() int32 {
	if x != nil {
		return x.xxx_hidden_MaxAttempts
	}
	return 0
}

func (x *LlmClientConfig) GetRetryDelaySeconds() int32 {
	if x != nil {
		return x.xxx_hidden_RetryDelaySeconds
	}
	return 0
}

func (x *LlmClientConfig) GetTools() *ToolConfig {
	if x != nil {
		return x.xxx_hidden_Tools
	}
	return nil
}

func (x *LlmClientConfig) GetLiteModel() string {
	if x != nil {
		if x.xxx_hidden_LiteModel != nil {
			return *x.xxx_hidden_LiteModel
		}
		return ""
	}
	return ""
}

func (x *LlmClientConfig) GetFastModel() string {
	if x != nil {
		if x.xxx_hidden_FastModel != nil {
			return *x.xxx_hidden_FastModel
		}
		return ""
	}
	return ""
}

func (x *LlmClientConfig) GetProModel() string {
	if x != nil {
		if x.xxx_hidden_ProModel != nil {
			return *x.xxx_hidden_ProModel
		}
		return ""
	}
	return ""
}

func (x *LlmClientConfig) SetTimeoutPerRequestSeconds(v int32) {
	x.xxx_hidden_TimeoutPerRequestSeconds = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *LlmClientConfig) SetMaxAttempts(v int32) {
	x.xxx_hidden_MaxAttempts = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *LlmClientConfig) SetRetryDelaySeconds(v int32) {
	x.xxx_hidden_RetryDelaySeconds = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *LlmClientConfig) SetTools(v *ToolConfig) {
	x.xxx_hidden_Tools = v
}

func (x *LlmClientConfig) SetLiteModel(v string) {
	x.xxx_hidden_LiteModel = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *LlmClientConfig) SetFastModel(v string) {
	x.xxx_hidden_FastModel = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *LlmClientConfig) SetProModel(v string) {
	x.xxx_hidden_ProModel = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *LlmClientConfig) HasTimeoutPerRequestSeconds() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LlmClientConfig) HasMaxAttempts() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LlmClientConfig) HasRetryDelaySeconds() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *LlmClientConfig) HasTools() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tools != nil
}

func (x *LlmClientConfig) HasLiteModel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *LlmClientConfig) HasFastModel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *LlmClientConfig) HasProModel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *LlmClientConfig) ClearTimeoutPerRequestSeconds() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TimeoutPerRequestSeconds = 0
}

func (x *LlmClientConfig) ClearMaxAttempts() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MaxAttempts = 0
}

func (x *LlmClientConfig) ClearRetryDelaySeconds() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_RetryDelaySeconds = 0
}

func (x *LlmClientConfig) ClearTools() {
	x.xxx_hidden_Tools = nil
}

func (x *LlmClientConfig) ClearLiteModel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_LiteModel = nil
}

func (x *LlmClientConfig) ClearFastModel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_FastModel = nil
}

func (x *LlmClientConfig) ClearProModel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_ProModel = nil
}

type LlmClientConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Timeout for each request to the LLM.
	// Default: 240 (4 minutes)
	TimeoutPerRequestSeconds *int32
	// Maximum number of attempts to run the agent.
	// Default: 3
	MaxAttempts *int32
	// Delay between retries.
	// Default: 10
	RetryDelaySeconds *int32
	// Configuration for the tools that the LLM agent can use.
	Tools *ToolConfig
	// Abstraction for a lite model.
	// Default: gemini-3.5-flash-lite
	LiteModel *string
	// Abstraction for a fast model.
	// Default: gemini-3.6-flash
	FastModel *string
	// Abstraction for a pro model.
	// Default: gemini-3.1-pro-preview
	ProModel *string
}

func (b0 LlmClientConfig_builder) Build() *LlmClientConfig {
	m0 := &LlmClientConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TimeoutPerRequestSeconds != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_TimeoutPerRequestSeconds = *b.TimeoutPerRequestSeconds
	}
	if b.MaxAttempts != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_MaxAttempts = *b.MaxAttempts
	}
	if b.RetryDelaySeconds != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_RetryDelaySeconds = *b.RetryDelaySeconds
	}
	x.xxx_hidden_Tools = b.Tools
	if b.LiteModel != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_LiteModel = b.LiteModel
	}
	if b.FastModel != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_FastModel = b.FastModel
	}
	if b.ProModel != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_ProModel = b.ProModel
	}
	return m0
}

type ToolConfig struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HttpClientConfig *HttpClientConfig      `protobuf:"bytes,1,opt,name=http_client_config,json=httpClientConfig,proto3,oneof"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ToolConfig) Reset() {
	*x = ToolConfig{}
	mi := &file_llm_client_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolConfig) ProtoMessage() {}

func (x *ToolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_llm_client_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolConfig) GetHttpClientConfig() *HttpClientConfig {
	if x != nil {
		return x.xxx_hidden_HttpClientConfig
	}
	return nil
}

func (x *ToolConfig) SetHttpClientConfig(v *HttpClientConfig) {
	x.xxx_hidden_HttpClientConfig = v
}

func (x *ToolConfig) HasHttpClientConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HttpClientConfig != nil
}

func (x *ToolConfig) ClearHttpClientConfig() {
	x.xxx_hidden_HttpClientConfig = nil
}

type ToolConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	HttpClientConfig *HttpClientConfig
}

func (b0 ToolConfig_builder) Build() *ToolConfig {
	m0 := &ToolConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_HttpClientConfig = b.HttpClientConfig
	return m0
}

// Configuration for the HTTP client tool. Note that the tool uses the core
// HTTP client, and thus these options do not need to be duplicated.
type HttpClientConfig struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AllowedMethods        []string               `protobuf:"bytes,1,rep,name=allowed_methods,json=allowedMethods,proto3"`
	xxx_hidden_MaxRequestsPerService int32                  `protobuf:"varint,2,opt,name=max_requests_per_service,json=maxRequestsPerService,proto3,oneof"`
	xxx_hidden_MaxAnswerSizeBytes    int32                  `protobuf:"varint,3,opt,name=max_answer_size_bytes,json=maxAnswerSizeBytes,proto3,oneof"`
	xxx_hidden_ForbiddenPaths        []string               `protobuf:"bytes,4,rep,name=forbidden_paths,json=forbiddenPaths,proto3"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *HttpClientConfig) Reset() {
	*x = HttpClientConfig{}
	mi := &file_llm_client_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpClientConfig) ProtoMessage() {}

func (x *HttpClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_llm_client_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpClientConfig) GetAllowedMethods() []string {
	if x != nil {
		return x.xxx_hidden_AllowedMethods
	}
	return nil
}

func (x *HttpClientConfig) GetMaxRequestsPerService() int32 {
	if x != nil {
		return x.xxx_hidden_MaxRequestsPerService
	}
	return 0
}

func (x *HttpClientConfig) GetMaxAnswerSizeBytes() int32 {
	if x != nil {
		return x.xxx_hidden_MaxAnswerSizeBytes
	}
	return 0
}

func (x *HttpClientConfig) GetForbiddenPaths() []string {
	if x != nil {
		return x.xxx_hidden_ForbiddenPaths
	}
	return nil
}

func (x *HttpClientConfig) SetAllowedMethods(v []string) {
	x.xxx_hidden_AllowedMethods = v
}

func (x *HttpClientConfig) SetMaxRequestsPerService(v int32) {
	x.xxx_hidden_MaxRequestsPerService = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *HttpClientConfig) SetMaxAnswerSizeBytes(v int32) {
	x.xxx_hidden_MaxAnswerSizeBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *HttpClientConfig) SetForbiddenPaths(v []string) {
	x.xxx_hidden_ForbiddenPaths = v
}

func (x *HttpClientConfig) HasMaxRequestsPerService() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *HttpClientConfig) HasMaxAnswerSizeBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *HttpClientConfig) ClearMaxRequestsPerService() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MaxRequestsPerService = 0
}

func (x *HttpClientConfig) ClearMaxAnswerSizeBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MaxAnswerSizeBytes = 0
}

type HttpClientConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// List of HTTP methods that the agent is allowed to use.
	// Default: ["GET", "POST"]
	AllowedMethods []string
	// Maximum number of HTTP requests per network service that the agent is
	// allowed to make.
	// Default: 50
	MaxRequestsPerService *int32
	// Maximum size of an HTTP response body to pass to the agent.
	// Default: 1048576 (1MB)
	MaxAnswerSizeBytes *int32
	// Forbidden paths regexps. If the agent tries to request a path that matches
	// any of these regexps, the request will be rejected.
	// Default: [".*abort.*", ".*delete.*", ".*drop.*", ".*huphuphup.*",
	// ".*kill.*", ".*quit.*", ".*remove.*"]
	ForbiddenPaths []string
}

func (b0 HttpClientConfig_builder) Build() *HttpClientConfig {
	m0 := &HttpClientConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AllowedMethods = b.AllowedMethods
	if b.MaxRequestsPerService != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_MaxRequestsPerService = *b.MaxRequestsPerService
	}
	if b.MaxAnswerSizeBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_MaxAnswerSizeBytes = *b.MaxAnswerSizeBytes
	}
	x.xxx_hidden_ForbiddenPaths = b.ForbiddenPaths
	return m0
}

var File_llm_client_config_proto protoreflect.FileDescriptor

const file_llm_client_config_proto_rawDesc = "" +
	"\n" +
	"\x17llm_client_config.proto\x12\x1dgoonami.proto.configs.clients\"\xe1\x03\n" +
	"\x0fLlmClientConfig\x12B\n" +
	"\x1btimeout_per_request_seconds\x18\x01 \x01(\x05H\x00R\x18timeoutPerRequestSeconds\x88\x01\x01\x12&\n" +
	"\fmax_attempts\x18\x02 \x01(\x05H\x01R\vmaxAttempts\x88\x01\x01\x123\n" +
	"\x13retry_delay_seconds\x18\x03 \x01(\x05H\x02R\x11retryDelaySeconds\x88\x01\x01\x12D\n" +
	"\x05tools\x18\x04 \x01(\v2).goonami.proto.configs.clients.ToolConfigH\x03R\x05tools\x88\x01\x01\x12\"\n" +
	"\n" +
	"lite_model\x18\x05 \x01(\tH\x04R\tliteModel\x88\x01\x01\x12\"\n" +
	"\n" +
	"fast_model\x18\x06 \x01(\tH\x05R\tfastModel\x88\x01\x01\x12 \n" +
	"\tpro_model\x18\a \x01(\tH\x06R\bproModel\x88\x01\x01B\x1e\n" +
	"\x1c_timeout_per_request_secondsB\x0f\n" +
	"\r_max_attemptsB\x16\n" +
	"\x14_retry_delay_secondsB\b\n" +
	"\x06_toolsB\r\n" +
	"\v_lite_modelB\r\n" +
	"\v_fast_modelB\f\n" +
	"\n" +
	"_pro_model\"\x87\x01\n" +
	"\n" +
	"ToolConfig\x12b\n" +
	"\x12http_client_config\x18\x01 \x01(\v2/.goonami.proto.configs.clients.HttpClientConfigH\x00R\x10httpClientConfig\x88\x01\x01B\x15\n" +
	"\x13_http_client_config\"\x91\x02\n" +
	"\x10HttpClientConfig\x12'\n" +
	"\x0fallowed_methods\x18\x01 \x03(\tR\x0eallowedMethods\x12<\n" +
	"\x18max_requests_per_service\x18\x02 \x01(\x05H\x00R\x15maxRequestsPerService\x88\x01\x01\x126\n" +
	"\x15max_answer_size_bytes\x18\x03 \x01(\x05H\x01R\x12maxAnswerSizeBytes\x88\x01\x01\x12'\n" +
	"\x0fforbidden_paths\x18\x04 \x03(\tR\x0eforbiddenPathsB\x1b\n" +
	"\x19_max_requests_per_serviceB\x18\n" +
	"\x16_max_answer_size_bytesB\x98\x01\n" +
	"(com.google.goonami.proto.configs.clientsB\x19LlmClientConfigOuterClassP\x01ZOgithub.com/google/goonami-scanner/common/clients/llm/llm_client_config_go_protob\x06proto3"

var file_llm_client_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_llm_client_config_proto_goTypes = []any{
	(*LlmClientConfig)(nil),  // 0: goonami.proto.configs.clients.LlmClientConfig
	(*ToolConfig)(nil),       // 1: goonami.proto.configs.clients.ToolConfig
	(*HttpClientConfig)(nil), // 2: goonami.proto.configs.clients.HttpClientConfig
}
var file_llm_client_config_proto_depIdxs = []int32{
	1, // 0: goonami.proto.configs.clients.LlmClientConfig.tools:type_name -> goonami.proto.configs.clients.ToolConfig
	2, // 1: goonami.proto.configs.clients.ToolConfig.http_client_config:type_name -> goonami.proto.configs.clients.HttpClientConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_llm_client_config_proto_init() }
func file_llm_client_config_proto_init() {
	if File_llm_client_config_proto != nil {
		return
	}
	file_llm_client_config_proto_msgTypes[0].OneofWrappers = []any{}
	file_llm_client_config_proto_msgTypes[1].OneofWrappers = []any{}
	file_llm_client_config_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_client_config_proto_rawDesc), len(file_llm_client_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llm_client_config_proto_goTypes,
		DependencyIndexes: file_llm_client_config_proto_depIdxs,
		MessageInfos:      file_llm_client_config_proto_msgTypes,
	}.Build()
	File_llm_client_config_proto = out.File
	file_llm_client_config_proto_goTypes = nil
	file_llm_client_config_proto_depIdxs = nil
}
