//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: llm_client_config.proto

package llm_client_config_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LlmClientConfig struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TimeoutPerRequestSec int32                  `protobuf:"varint,1,opt,name=timeout_per_request_sec,json=timeoutPerRequestSec,proto3"`
	xxx_hidden_MaxAttempts          int32                  `protobuf:"varint,2,opt,name=max_attempts,json=maxAttempts,proto3"`
	xxx_hidden_RetryDelaySec        int32                  `protobuf:"varint,3,opt,name=retry_delay_sec,json=retryDelaySec,proto3"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *LlmClientConfig) Reset() {
	*x = LlmClientConfig{}
	mi := &file_llm_client_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LlmClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LlmClientConfig) ProtoMessage() {}

func (x *LlmClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_llm_client_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LlmClientConfig) GetTimeoutPerRequestSec() int32 {
	if x != nil {
		return x.xxx_hidden_TimeoutPerRequestSec
	}
	return 0
}

func (x *LlmClientConfig) GetMaxAttempts() int32 {
	if x != nil {
		return x.xxx_hidden_MaxAttempts
	}
	return 0
}

func (x *LlmClientConfig) GetRetryDelaySec() int32 {
	if x != nil {
		return x.xxx_hidden_RetryDelaySec
	}
	return 0
}

func (x *LlmClientConfig) SetTimeoutPerRequestSec(v int32) {
	x.xxx_hidden_TimeoutPerRequestSec = v
}

func (x *LlmClientConfig) SetMaxAttempts(v int32) {
	x.xxx_hidden_MaxAttempts = v
}

func (x *LlmClientConfig) SetRetryDelaySec(v int32) {
	x.xxx_hidden_RetryDelaySec = v
}

type LlmClientConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Timeout for each request to the LLM.
	TimeoutPerRequestSec int32
	// Maximum number of attempts to run the agent.
	MaxAttempts int32
	// Delay between retries.
	RetryDelaySec int32
}

func (b0 LlmClientConfig_builder) Build() *LlmClientConfig {
	m0 := &LlmClientConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TimeoutPerRequestSec = b.TimeoutPerRequestSec
	x.xxx_hidden_MaxAttempts = b.MaxAttempts
	x.xxx_hidden_RetryDelaySec = b.RetryDelaySec
	return m0
}

var File_llm_client_config_proto protoreflect.FileDescriptor

const file_llm_client_config_proto_rawDesc = "" +
	"\n" +
	"\x17llm_client_config.proto\x12\x1dgoonami.proto.configs.clients\"\x93\x01\n" +
	"\x0fLlmClientConfig\x125\n" +
	"\x17timeout_per_request_sec\x18\x01 \x01(\x05R\x14timeoutPerRequestSec\x12!\n" +
	"\fmax_attempts\x18\x02 \x01(\x05R\vmaxAttempts\x12&\n" +
	"\x0fretry_delay_sec\x18\x03 \x01(\x05R\rretryDelaySecB\x98\x01\n" +
	"(com.google.goonami.proto.configs.clientsB\x19LlmClientConfigOuterClassP\x01ZOgithub.com/google/goonami-scanner/common/clients/llm/llm_client_config_go_protob\x06proto3"

var file_llm_client_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_llm_client_config_proto_goTypes = []any{
	(*LlmClientConfig)(nil), // 0: goonami.proto.configs.clients.LlmClientConfig
}
var file_llm_client_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_llm_client_config_proto_init() }
func file_llm_client_config_proto_init() {
	if File_llm_client_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_client_config_proto_rawDesc), len(file_llm_client_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llm_client_config_proto_goTypes,
		DependencyIndexes: file_llm_client_config_proto_depIdxs,
		MessageInfos:      file_llm_client_config_proto_msgTypes,
	}.Build()
	File_llm_client_config_proto = out.File
	file_llm_client_config_proto_goTypes = nil
	file_llm_client_config_proto_depIdxs = nil
}
