//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: callbackserver_client_config.proto

package callbackserver_client_config_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallbackServerClientConfig struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CallbackAddress *string                `protobuf:"bytes,1,opt,name=callback_address,json=callbackAddress,proto3,oneof"`
	xxx_hidden_CallbackPort    int32                  `protobuf:"varint,2,opt,name=callback_port,json=callbackPort,proto3,oneof"`
	xxx_hidden_PollingBaseUrl  *string                `protobuf:"bytes,3,opt,name=polling_base_url,json=pollingBaseUrl,proto3,oneof"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CallbackServerClientConfig) Reset() {
	*x = CallbackServerClientConfig{}
	mi := &file_callbackserver_client_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackServerClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackServerClientConfig) ProtoMessage() {}

func (x *CallbackServerClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_callbackserver_client_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CallbackServerClientConfig) GetCallbackAddress() string {
	if x != nil {
		if x.xxx_hidden_CallbackAddress != nil {
			return *x.xxx_hidden_CallbackAddress
		}
		return ""
	}
	return ""
}

func (x *CallbackServerClientConfig) GetCallbackPort() int32 {
	if x != nil {
		return x.xxx_hidden_CallbackPort
	}
	return 0
}

func (x *CallbackServerClientConfig) GetPollingBaseUrl() string {
	if x != nil {
		if x.xxx_hidden_PollingBaseUrl != nil {
			return *x.xxx_hidden_PollingBaseUrl
		}
		return ""
	}
	return ""
}

func (x *CallbackServerClientConfig) SetCallbackAddress(v string) {
	x.xxx_hidden_CallbackAddress = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *CallbackServerClientConfig) SetCallbackPort(v int32) {
	x.xxx_hidden_CallbackPort = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *CallbackServerClientConfig) SetPollingBaseUrl(v string) {
	x.xxx_hidden_PollingBaseUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CallbackServerClientConfig) HasCallbackAddress() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CallbackServerClientConfig) HasCallbackPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CallbackServerClientConfig) HasPollingBaseUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CallbackServerClientConfig) ClearCallbackAddress() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CallbackAddress = nil
}

func (x *CallbackServerClientConfig) ClearCallbackPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CallbackPort = 0
}

func (x *CallbackServerClientConfig) ClearPollingBaseUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_PollingBaseUrl = nil
}

type CallbackServerClientConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The address of the callback server (domain or IP).
	CallbackAddress *string
	// The port of the callback server.
	CallbackPort *int32
	// The base URL for polling interaction results.
	PollingBaseUrl *string
}

func (b0 CallbackServerClientConfig_builder) Build() *CallbackServerClientConfig {
	m0 := &CallbackServerClientConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CallbackAddress != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_CallbackAddress = b.CallbackAddress
	}
	if b.CallbackPort != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_CallbackPort = *b.CallbackPort
	}
	if b.PollingBaseUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_PollingBaseUrl = b.PollingBaseUrl
	}
	return m0
}

var File_callbackserver_client_config_proto protoreflect.FileDescriptor

const file_callbackserver_client_config_proto_rawDesc = "" +
	"\n" +
	"\"callbackserver_client_config.proto\x12\x1dgoonami.proto.configs.clients\"\xe1\x01\n" +
	"\x1aCallbackServerClientConfig\x12.\n" +
	"\x10callback_address\x18\x01 \x01(\tH\x00R\x0fcallbackAddress\x88\x01\x01\x12(\n" +
	"\rcallback_port\x18\x02 \x01(\x05H\x01R\fcallbackPort\x88\x01\x01\x12-\n" +
	"\x10polling_base_url\x18\x03 \x01(\tH\x02R\x0epollingBaseUrl\x88\x01\x01B\x13\n" +
	"\x11_callback_addressB\x10\n" +
	"\x0e_callback_portB\x13\n" +
	"\x11_polling_base_urlB\xb9\x01\n" +
	"(com.google.goonami.proto.configs.clientsB$CallbackServerClientConfigOuterClassP\x01Zegithub.com/google/goonami-scanner/common/clients/callbackserver/callbackserver_client_config_go_protob\x06proto3"

var file_callbackserver_client_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_callbackserver_client_config_proto_goTypes = []any{
	(*CallbackServerClientConfig)(nil), // 0: goonami.proto.configs.clients.CallbackServerClientConfig
}
var file_callbackserver_client_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_callbackserver_client_config_proto_init() }
func file_callbackserver_client_config_proto_init() {
	if File_callbackserver_client_config_proto != nil {
		return
	}
	file_callbackserver_client_config_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_callbackserver_client_config_proto_rawDesc), len(file_callbackserver_client_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_callbackserver_client_config_proto_goTypes,
		DependencyIndexes: file_callbackserver_client_config_proto_depIdxs,
		MessageInfos:      file_callbackserver_client_config_proto_msgTypes,
	}.Build()
	File_callbackserver_client_config_proto = out.File
	file_callbackserver_client_config_proto_goTypes = nil
	file_callbackserver_client_config_proto_depIdxs = nil
}
